Main Page 
Algeria 
Kano 
Gangleri 
Administrators 
Taichi 
koavf 
Nigeria 
Jon Harald Søby 
Dcljr 
Bible 
United States 
Jesus 
Christianity 
Zaria 
Jose77 
BOT-Superzerocool 
A12n 
Human rights 
Ten Commandments 
Xandi 
List of sovereign states 
Religion 
Quastr 
Robbot 
Stub 
Mošovce 
Slovakia 
Thijs!bot 
TXiKiBoT 
Db 
JAnDbot 
True Jesus Church 
Kelovy 
Vargenau 
Escarbot 
Mithridates 
ReyBrujo 
ReyBrujo/Dumps 
Candidates for speedy deletion 
Stubs 
IPA 
Unicode 
Purodha 
VolkovBot 
EDUCA33E 
Sa'adu Zungur 
Earth 
Byrialbot 
Siebrand 
SieBot 
Community portal 
BotMultichill 
Multichill 
Natsubee 
Jorunn 
PipepBot 
Infobox country 
! 
Katsina State 
ScooterDe 
AlleborgoBot 
Soman 
Razorflame 
Alexsh 
Bot 
Benazir Bhutto 
Desmond Tutu 
Abubakar Imam 
Purbo T 
Carkuni 
Kanesue 
Statistics 
Jayvdb 
Junafani 
ZorroIII 
Caiaffa 
Darev 
United Kingdom 
Cuaxdon 
MenoBot 
Law soma 
Curitiba 
WikiDreamer 
WikiDreamer Bot 
Israel 
Nelson Mandela 
Hausa Kingdoms 
Końskowola 
GerardM/Africa 
MoiraMoira 
Image label begin 
Image label small 
Image label end 
Infobox language/codelist 
Image label 
Europe and seas labelled map 
Europe 
Col-begin 
Col-break 
Col-end 
See also 
Vital articles/Level/2 
TXiKi 
HerculeBot 
とある白い猫 
タチコマ robot 
Barack Obama 
Cambodia 
Adolfobs93 
Ptbotgourou 
Dmitri Lytov 
DragonBot 
Mamman Shata 
Horst 
Polio 
Kofi Annan 
Agadez 
Muro Bot 
Muro de Aguas 
Hugo.arg 
Sebleouf 
Eivindgh 
Sudan 
Chad 
Human 
Africa 
Mali 
Niger 
Cameroon 
MediaWiki default 
Gospel of Matthew 
Benin 
Togo 
Burkina Faso 
Guinea 
JøMa 
Ethiopia 
Kenya 
Uganda 
Senegal 
Libya 
France 
Iran 
Mahmoud Ahmadinejad 
Japan 
India 
China 
Palestinian National Authority 
Camel 
Gaza Strip 
Angola 
らぼるぺ 
Asia 
Pakistan 
Chameleon 
Australia 
Animal 
Dog 
Fish 
Elephant 
Chicken 
Bird 
Mercy 
ArthurBot 
Butterfly 
Pale fox 
Lion 
Bee 
Bear 
Eagle 
Livestock 
Botswana 
Deer 
Mosquito 
Blattodea 
Donkey 
Internet 
Burundi 
Canary Islands 
Darkicebot 
Hausa people 
Anoopan 
SilvonenBot 
Djsasso 
SassoBot 
Idioma-bot 
Chobot 
Luckas-bot 
Contents 
Kaduna State 
Amina 
Zamfara State 
Katsina 
Almabot 
Refrigerator 
Clock 
Ajami script 
Continent 
CERminator 
Mdavid89 
African Americans 
Soft redirect 
RoggBot 
Financial crisis 
Documentation 
Flag 
Flag data 
Flag/core 
Country data Nigeria 
Country showdata 
Hatnote 
Divbox 
Mbox templates 
Navbox 
Navbar 
Tl 
Purge 
Template link expanded 
Nuclear weapon 
Mbox 
Namespace detect 
Ombox 
Ombox/core 
Ambox 
Ambox/core 
Tmbox 
If 
Nigeria 
Reflist 
Democratic Republic of the Congo 
Maiduguri 
Domestic pig 
Dan Maraya 
Islam 
FoxBot 
Egypt 
Commons category 
Confucius 
International Criminal Court 
Germany 
Machu Picchu 
Uusijani 
Muhammadu Buhari 
Ahmadu Bello 
Masti 
Arseny1992 
Moussa Dadis Camara 
Choung 
I utqoreli I 
Cancer 
Zinedine Zidane 
Script/Nastaliq 
United Nations 
Selena 
Europe 
Margaret Thatcher 
Facebook 
Nobel Prize 
International Committee of the Red Cross 
Bauchi State 
sj 
The Simpsons 
Poland 
Jfblanc 
Emijrp/List of Wikipedians by number of edits 
JAn Dudík 
Canada 
OffsBlink 
Ruhollah Khomeini 
Fernando Alonso 
CarsracBot 
Carsrac 
Dala, Kano 
JhsBot 
Adolf Hitler 
Umaru Musa Yar'Adua 
Dong Hoi Airport 
Tan Son Nhat International Airport 
Vietnam 
Avicennasis 
ITA 
Foxie001 
Esperanto 
ZéroBot 
Kanjy 
SreeBot 
Animals 
Northern giraffe 
Fish 
Tilapia 
Gymnarchus 
Clarias anguillaris 
West African lungfish 
Monkey 
Monkeys 
Olive baboon 
Grivet 
Snake 
Turtle 
Crocodilia 
Xerus erythropus 
Red-fronted gazelle 
Common duiker 
Red-flanked duiker 
Golden jackal 
Harnessed bushbuck 
Gambian pouched rat 
Roan antelope 
Leopard 
African civet 
Oribi 
Aardvark 
Birds 
Red-billed quelea 
Village weaver 
White-faced whistling duck 
Abyssinian roller 
Bustard 
Speckled pigeon 
Abdim's stork 
White stork 
African grey hornbill 
Spur-winged goose 
Black crowned crane 
Red-cheeked cordon-bleu 
Black-crowned tchagra 
Pied crow 
Fulvous whistling duck 
Cat 
Tree 
Trees 
Garlic 
Luffa 
Common wheat 
Moringa oleifera 
Salvadora persica 
Andropogon gayanus 
Ziziphus mucronata 
Indigofera 
Cyperus esculentus 
Basil 
Cucurbita pepo 
Ximenia americana 
Maize 
Tamarind 
Cassava 
Yam 
Ceiba pentandra 
Momordica balsamina 
Guava 
Okra 
Taro 
Datura stramonium 
Sesame 
Ricinus 
Xylopia aethiopica 
Religion 
1 
2 
3 
4 
5 
6 
7 
8 
9 
10 
20 
40 
30 
1000 
Numbers 
Fruit 
Sclerocarya birrea 
Cut-throat finch 
Streptopelia 
Marabou stork 
Pied kingfisher 
Common ostrich 
Oxpecker 
Guineafowl 
Cattle egret 
Eurasian hoopoe 
Black-headed lapwing 
Diospyros mespiliformis 
Amaranthus viridis 
Borassus aethiopum 
Adansonia digitata 
African buffalo 
Black rhinoceros 
Honey badger 
Black-necked spitting cobra 
Earth 
Chemistry 
Africa 
User tr 
User tr 
Babel 
User tr-N 
Wikipedians by language 
Wikipedia 
User af-1 
User af 
User af-1 
User en-2 
User en 
User en-2 
User ha 
User ha 
User ha-N 
Manumg 
Manubot 
User als-1 
User als 
User als-1 
User ar-1 
User ar 
User ar-1 
User ast-1 
User ast 
User ast-1 
User az 
User az 
User az-N 
User bar-1 
User bar 
User bar-1 
User be-2 
User be 
User be-2 
User bg-1 
User bg 
User bg-1 
User ca-1 
User ca 
User ca-1 
User ca-4 
User ca-4 
User cs-1 
User cs 
User cs-1 
User da 
User da 
User da-N 
User da-1 
User da-1 
User da-2 
User da-2 
User de 
User de 
User de-1 
User de-1 
User de-2 
User de-2 
User de-3 
User de-3 
User el 
User el 
User el-N 
User el-1 
User el-1 
User en 
User en-N 
User en-1 
User en-1 
User en-3 
User en-3 
User en-4 
User en-4 
User tr-2 
User tr-2 
Pigeon pea 
Osasco 
EmausBot 
Oslac 
Cà Mau Airport 
Beaukarpo 
Hausa people 
Hausa language 
Mod 
Zaghawa language 
Axpde 
CocuBot 
Cocu 
Marek69 
Plant 
Plants 
PixelBot 
DEagleBot 
Rezabot 
Zemant 
Paltoga 
Russia 
Berlin 
Vago 
Xic667 
Mauritania 
Da Nang International Airport 
Disambiguation 
Moshchena 
Yulia Savicheva 
Saratov 
NjardarBot 
Lixer 
JYBot 
AvicBot 
Njardarlogar 
AvocatoBot 
Turkey 
Alexander Mikhalenko 
Seti6908 
Asia 
Chile 
Santiago 
Buenos Aires 
Lima 
Montevideo 
São Paulo 
Rio de Janeiro 
User uk 
User uk-N 
Boko Haram 
Tho Xuan Airport 
Almajiranci 
Makecat 
Fajrbot 
Nickispeaki 
User uk 
MahdiBot 
Ido 
Rainbow 
Air 
Stable 
Folktale 
Sea 
Love 
Proverb 
Technology 
Giade 
Tornado 
Water 
Concepción, Chile 
Kolega2357 
Aladdin Ali Baba 
تفکر 
Turkey 
South Africa 
South Africa 
Mathematics 
CFA franc 
Currency 
Nana Asmaʼu 
Muhammad 
Ibrahim Shema 
Maxval 
Villeneuve-d'Ascq 
ESB Villeneuve-d'Ascq 
Al-Bidaya wa'l-Nihaya 
Deafness 
Marek Grechuta 
Sung Jae-gi 
Apache HTTP Server 
Car 
Bus 
Airplane 
Chulipuram 
Jaffna 
Sri Lanka 
Maldives 
Bhutan 
Bangladesh 
Nepal 
Afghanistan 
Malaysia 
Indonesia 
Philippines 
Singapore 
Myanmar 
Vietnam 
Thailand 
Laos 
Brunei 
Hong Kong 
Macau 
Mongolia 
North Korea 
South Korea 
Taiwan 
Kazakhstan 
Kyrgyzstan 
Tajikistan 
Uzbekistan 
Turkmenistan 
East Timor 
Armenia 
Azerbaijan 
Bahrain 
Cyprus 
Iraq 
Jordan 
Oman 
Kuwait 
Lebanon 
Qatar 
Saudi Arabia 
Syria 
United Arab Emirates 
Yemen 
Switzerland 
Iceland 
Republic of Ireland 
Denmark 
Finland 
Norway 
Sweden 
Austria 
Italy 
Ukraine 
Portugal 
Belgium 
Greece 
Bulgaria 
Czech Republic 
Hungary 
Moldova 
Romania 
Slovakia 
Albania 
Lithuania 
Latvia 
Jersey 
Åland Islands 
Estonia 
Bailiwick of Guernsey 
Isle of Man 
North Macedonia 
Malta 
Andorra 
Herzegovina 
Gibraltar 
Croatia 
Vatican City 
Montenegro 
San Marino 
Serbia 
Wikipedia 
Slovenia 
Liechtenstein 
Luxembourg 
Monaco 
Userbox 
Netherlands 
Walter Abbott 
Pawel Abbott 
Steve Abbley 
Keith Abbis 
Zema Abbey 
Nathan Abbey 
Ron Abbott 
Ben Abbey 
John Abbotts 
Chris Abel 
Graham Abel 
Samuel Abel 
Yemi Abiodun 
James Abrahams 
Laurie Abrahams 
Paul Abrahams 
Laurence Abrams 
Brian Abrey 
John Abthorpe 
Kenny Achampong 
Ernie Ackerley 
George Ackerley 
Tony Ackerman 
Mike Acland 
Alan A'Court 
Jack Acquroff 
Basil Acres 
Alec Acton 
Blair Adams 
Micky Adams 
Nathan Adams 
Nicky Adams 
Rod Adams 
Tony Adams 
Chris Adamson 
Harry Adamson 
Jimmy Adamson 
Keith Adamson 
Terry Adamson 
Charles Adcock 
Hugh Adcock 
Paul Adcock 
Tony Adcock 
Jack Addenbrooke 
Bert Addinall 
Percy Addinall 
Colin Addison 
Miles Addison 
George Addy 
Mike Addy 
Sam Adekugbe 
Hakeeb Adelakun 
Charles Ademeno 
George Adey 
Tom Adey 
Wilfred Adey 
Tom Adeyemi 
Kwame Adjeman-Pamboe 
Nigel Adkins 
Leslie Adlam 
Steve Adlard 
James Adlington 
Terry Adlington 
Albert Adomah 
Les Afful 
Benik Afobe 
Tony Agana 
Alf Agar 
Nat Agar 
Kieran Agard 
Steve Agnew 
Junior Agogo 
Patrick Agyemang 
Adnan Ahmed 
Shahed Ahmed 
Paul Aimson 
Roger Aindow 
Simon Ainge 
Alan Ainscow 
Andy Ainscow 
George Ainsley 
Alf Ainsworth 
Edgar Ainsworth 
Fred Ainsworth 
Gareth Ainsworth 
Lionel Ainsworth 
Phil Airey 
Sam Aiston 
Sydney Aistrup 
Barrie Aitchison 
Peter Aitchison 
Korede Aiyegbusi 
Toby Ajala 
Nicky Ajose 
Stephen Akers 
Vic Akers 
John Akinde 
Adebayo Akinfenwa 
Lucas Akins 
Chuba Akpom 
Cliff Akurang 
Brian Albeson 
Carl Airey 
Frank Airey 
Marc Albrighton 
Mark Albrighton 
Bill Albury 
Colin Alcide 
Charles W. Alcock 
Craig Alcock 
Danny Alcock 
Harry Alcock 
Terry Alcock 
Albert Alderman 
Jack Alderson 
Richard Alderson 
Stuart Alderson 
Tom Alderson 
Jim Alderton 
Rio Alderton 
Peter Aldis 
Stan Aldous 
Albert Aldridge 
John Aldridge 
Martin Aldridge 
Paul Aldridge 
Milija Aleksic 
Lewis Alessandra 
Dennis Alexander 
Graham Alexander 
Greg Abbott 
Harry Abbott 
Jack Abbott 
James Abbott 
Peter Abbott 
Shirley Abbott 
William Abbott 
Gary Ablett 
John Ackroyd 
John Ackroyd 
Jamil Adam 
Amos Adams 
Bill Adams 
Bill Adams 
Billy Adams 
Billy Adams 
Bob Adams 
Brian Adams 
Charlee Adams 
Charlie Adams 
Craig Adams 
Darren Adams 
Don Adams 
Edward Adams 
Danny Adams 
Frank Adams 
Graham Adams 
Jimmy Adams 
Neil Adams 
Rex Adams 
Steve Adams 
Steve Adams 
Ted Adams 
Walter Adams 
William Adams 
Dave Adamson 
John Addenbrooke 
Sam Adkins 
Charles Ainsworth 
Andrew Aitken 
Glenn Aitken 
Akala 
George Akers 
Edward Alcock 
Gabriel Agbonlahor 
Jimmy Aggrey 
George Albinson 
Nasarawa, Kano State 
Food 
Cite web 
Citation/CS1 
Citation/CS1/Configuration 
Citation/CS1/Whitelist 
Citation/CS1/Date validation 
Pp-template 
= 
Ronald Reagan 
North America 
Trojany, Masovian Voivodeship 
Charles Allan 
Charles Ambler 
Charlie Allen 
Charlie Amery 
Chris Allen 
Chris Allen 
Chris Anderson 
Chuks Aneke 
Clive Allen 
Colin Anderson 
Craig Allardyce 
Damien Allen 
Dan Allsopp 
Danny Allen-Page 
Danny Andrew 
Darren Ambrose 
Darren Anderson 
Darren Anderton 
Darren Angell 
Darren Annon 
David Allison 
David Amoo 
Dele Alli 
Dennis Allen 
Dick Allman 
Doug Allder 
Doug Allison 
Edward Allen 
Elijah Allsopp 
Eric Anderson 
Frank Alford 
Frank Allcock 
Frank Allen 
Geoff Anderson 
George Allen 
George Allon 
George Andrews 
George Ansell 
Gilbert Alsop 
Gillie Alldis 
Graham Allen 
Harry Anders 
Harry Anstiss 
Hasney Aljofree 
Henry Almond 
Ian Allinson 
Ian Andrews 
Iffy Allen 
Ijah Anderson 
Jack Allen 
Jack Allen 
Jack Almond 
Jack Ansell 
Jamie Allen 
Jamie Annerson 
Jermaine Anderson 
Jim Angell 
Jimmy Allen 
Jimmy Allen 
Jimmy Anders 
Joe Allen 
Joe Allon 
Joe Anderson 
John Allan 
John Allen 
John Allen 
John Almond 
John Anderton 
John Angus 
John Angus 
Jonny Allan 
Judan Ali 
Julian Alsford 
Julian Alsop 
Keith Alexander 
Keith Allen 
Keith Amos 
Kenny Allen 
Kevin Amankwaah 
Lee Andrews 
Lee Angol 
Leighton Allen 
Len Andrews 
Les Allen 
Les Ames 
Leslie Allman 
Louis Almond 
Malcolm Allison 
Manny Andruszewski 
Mark Allen 
Mark Allott 
Mark Anderson 
Mark Angel 
Martin Allen 
Myles Anderson 
Neil Allison 
Nick Anderson 
Oliver Allen 
Paul Allen 
Paul Anderson 
Percy Allen 
Percy Ames 
Percy Andrews 
Peter Allen 
Peter Anderson 
Peter Anderson 
Ralph Allen 
Reg Allen 
Richard Allsebrook 
Richard Annan 
Ricky Anane 
Ron Allen 
Ron Andrew 
Ronnie Allen 
Rory Allen 
Roy Ambler 
Rupert Anderson 
Russell Allen 
Ryan Allsop 
Ryan Amoo 
Sam Allardyce 
Sammy Ameobi 
Shola Ameobi 
Sone Aluko 
Stan Alexander 
Stan Anderson 
Jack Allan 
Stanley Amos 
Steve Anthrobus 
Stevland Angus 
Ted Anderson 
Terry Allcock 
Terry Anderson 
Terry Angus 
Thomas Allin 
Thomas Anderson 
Tim Alexander 
Tim Allpress 
Tom Allan 
Tomi Ameobi 
Tommy Allen 
Tommy Amphlett 
Tony Alexander 
Viv Anderson 
Walter Alsford 
Walter Amos 
Walter Anderson 
Wayne Allison 
Wayne Andrews 
William Allsop 
William Anderton 
Willie Almond 
Willie Anderson 
Zac Aley 
Calvin Andrew 
Calum Angus 
Brett Angell 
Brendel Anstey 
Bradley Allen 
Bobby Almond 
Bob Allen 
Billy Annis 
Billy Allen 
Bill Amor 
Bill Allcock 
Ben Amos 
Ben Alnwick 
Ben Algar 
Ashley Allanson 
Arthur Andrews 
Arthur Andrews 
Arthur Allman 
Andy Ansah 
Andy Allen 
Andrew Amos 
Alfred Ambler 
Alf Amos 
Albert Allen 
Adam Armstrong 
Adam Arthur 
Adem Atay 
Alan Ashman 
Alec Ashworth 
Alf Arrowsmith 
Alf Ashmore 
Alun Armstrong 
Andy Arnott 
Arthur Atkins 
Barry Ashworth 
Beaumont Asquith 
Ben Appleby 
Bill Appleyard 
Bill Arblaster 
Bill Asprey 
Bill Atkinson 
Billy Armfield 
Billy Ashcroft 
Billy Askew 
Bob Atkins 
Bobby Arber 
Brian Atkinson 
Carl Asaba 
Charlie Ashcroft 
Charlie Athersmith 
Chris Armstrong 
Chris Armstrong 
Chris Armstrong 
Chris Arthur 
Chris Atkinson 
Claude Ashton 
Colin Appleton 
Colin Askey 
Craig Armstrong 
Dalian Atkinson 
Dan Ashworth 
David Armstrong 
David Artell 
Dean Ashton 
Denis Atkins 
Derek Armstrong 
Derek Ashton 
Dick Armstrong 
Ed Asafu-Adjaye 
Eric Arnold 
Frank Arundel 
Frankie Artus 
Fred Appleyard 
Fred Atkinson 
Gary Armstrong 
George Antonio 
George Appleyard 
George Armitage 
George Armstrong 
George Ashall 
George Ashfield 
George Atkinson 
Gordon Armstrong 
Gordon Ashcroft 
Gordon Astall 
Gordon Atherton 
Harry Armitage 
Harry Armstrong 
Harry Arter 
Harry Ascroft 
Harry Ashby 
Harry Aston 
Herbert Ashton 
Herbie Arthur 
Horace Armitage 
Horace Astley 
Ian Arkwright 
Ian Armstrong 
Ian Ashbee 
Ivan Armes 
Jack Atherton 
Jack Atkin 
Jackie Arthur 
James Armstrong 
James Arnott 
James Ashmore 
James Atherton 
Jamie Ashdown 
Jeff Astle 
Jim Appleby 
Jim Arnold 
Jimmy Armfield 
Jimmy Ashall 
Jimmy Ashcroft 
Joe Anyinsah 
Joe Anyon 
Joe Armstrong 
Joe Ashley 
Joe Ashworth 
Joe Astley 
Joel Armstrong 
John Archer 
John Arnott 
John Ashdjian 
John Askey 
John Aspinall 
John Aston Sr. 
Jon Ashton 
Jon Ashton 
Jordan Archer 
Joseph Armstrong 
Joseph Ashworth 
Keith Armstrong 
Ken Armstrong 
Ken Ashbridge 
Kevin Arnott 
Kevin Ashley 
Kwesi Appiah 
Kyle Asante 
Lee Archer 
Lee Ashcroft 
Lee Atack 
Len Appleton 
Len Armitage 
Len Ashurst 
Len Astill 
Luke Ashworth 
Mark Atkins 
Matthew Armstrong 
Matty Appleby 
Michael Appleton 
Michail Antonio 
Mick Ash 
Mick Atkin 
Mike Astbury 
Moses Ashikodi 
Nathan Arnold 
Nathan Ashton 
Neal Ardley 
Neil Arndale 
Neil Ashton 
Neil Aspin 
Paul Arnison 
Paul Atkin 
Peter Atherton 
Philip Ashworth 
Reis Ashraf 
Rod Arnold 
Ron Ashman 
Ross Atkins 
Ryan Ashford 
Ryan Ashington 
Sam Ashton 
Sammy Armes 
Samuel Ashworth 
Smart Arridge 
Stephen Armstrong 
Stephen Arthurworrey 
Steve Arnold 
Steve Arnold 
Taiwo Atieno 
Teddy Ashton 
Terry Armstrong 
Thomas Armstrong 
Tommy Arkesden 
Tommy Arthern 
Tommy Aspden 
Tommy Atkin 
Tony Arins 
Tony Arrowsmith 
Troy Archibald-Henville 
Viv Aston 
Walter Ashmore 
Walter Atherton 
Warren Aspinall 
Will Antwi 
William Arnold 
Bill Ashurst 
Adam Baker 
Adam Barrett 
Adam Bartlett 
Ade Azeez 
Alan Banks 
Alan Barnett 
Albert Barrett 
Albert Bartlett 
Alex Bailey 
Alex Ball 
Alex Baptiste 
Alexander Barbour 
Alf Baker 
Alf Ball 
Allan Ball 
Amadou Bakayoko 
Amos Baddeley 
Andy Awford 
Andy Barcham 
Anthony Bardon 
Anthony Barness 
Arthur Attwood 
Arthur Bambridge 
Arthur Banner 
Ashley Barnes 
Ben Barnett 
Bert Badger 
Bert Barlow 
Bill Bainbridge 
Bill Baldwin 
Bill Barker 
Bill Barraclough 
Billy Austin 
Billy Ayre 
Billy Bairstow 
Billy Ball 
Billy Balmer 
Billy Bannister 
Billy Barnes 
Billy Barr 
Bob Bainbridge 
Bob Baldridge 
Bob Balmer 
Bob Barnshaw 
Bobby Ayre 
Bobby Barclay 
Bobby Barnes 
Bruce Bannister 
Callum Ball 
Carl Baker 
Carl Barrowclough 
Charles Baker 
Charles Bambridge 
Charlie Bannister 
Charlie Barnett 
Chris Balderstone 
Chris Banks 
Chris Barker 
Chris Bart-Williams 
Cis Baker 
Claude Barrett 
Cliff Balsom 
Clive Baker 
Colin Ayre 
Colin Barlow 
Colin Barnes 
Conrad Balatoni 
Corey Barnes 
Courtney Baker-Richardson 
Cyril Barlow 
Dale Banton 
Daniel Barrett 
Danny Bacon 
Danny Bailey 
Danny Bance 
Dave Bacuzzi 
Dave Bamber 
Dave Bampton 
Dave Barnett 
David Baillie 
David Bairstow 
David Ball 
David Bardsley 
David Barnes 
Dean Austin 
Dean Barrick 
Dennis Bailey 
Dennis Bailey 
Dominic Barclay 
Earl Barrett 
Eddie Baily 
Eddie Barks 
Eric Barnes 
Ernest Bambridge 
Francis Banks 
Frank Austin 
Frank Bailey 
Frank Barson 
Fred Avey 
Fred Barber 
Fred Baron 
Frederick Banks 
Gareth Barry 
Garry Williamson Barnes 
Gary Bannister 
Geoff Barker 
Geoff Barnett 
Geoff Barnsley 
Geoff Barrowcliffe 
George Ayres 
George Baddeley 
George Bakewell 
George Baldock 
George Baldwin 
George Barker 
George Barron 
Giles Barnes 
Gordon Banks 
Gordon Barker 
Graeme Atkinson 
Graham Atkinson 
Graham Bailey 
Harry Bagge 
Harry Baker 
Harry Barkas 
Harry Barratt 
Herbert Ayre 
Herbert Banks 
Horace Bailey 
Horace Barnes 
Ian Atkinson 
Ian Bailey 
Ian Baird 
Ian Banks 
Ian Baraclough 
Jack Atkinson 
Jack Badham 
Jack Bailey 
Jack Baldwin 
Jack Balmer 
Jack Bamber 
Jack Bannister 
Jack Barber 
Jack Barker 
Jack Barmby 
Jack Barnes 
Jack Barrett 
Jack Barthram 
James Bagshaw 
James Bailey 
James Baker 
James Banks 
Jamie Attwell 
Jamie Barnwell-Edinboro 
Jason Banks 
Jason Banton 
Jason Barnett 
Jeff Barker 
Jeff Barmby 
Jim Bannister 
Jim Barrett Jr. 
Jim Barrett Sr. 
Jim Barron 
Jimmy Banks 
Jimmy Bannister 
Jimmy Barrington 
Joe Bacuzzi 
Joe Bainbridge 
Joe Baker 
Joe Ball 
Joe Barratt 
John Atyeo 
John Baber 
John Bailey 
John Bailey 
John Bailey 
John Bain 
John Baines 
Jack Ball 
John Ball 
John Ballagher 
John Bamber 
John Barnes 
Johnny Ayris 
Jonathan Atkinson 
Joe Bache 
Joseph Baldwin 
Josh Atkinson 
Karl Austin 
Keith Ball 
Keith Bambridge 
Keith Bannister 
Keith Barber 
Keith Barker 
Ken Ayres 
Ken Bainbridge 
Ken Barnes 
Kenny Banks 
Kevin Ball 
Kevin Barnes 
Kevin Baron 
Kieron Baker 
Laurie Banfield 
Laurie Barnett 
Lea Barkus 
Lee Barnard 
Lee Barrow 
Leighton Baines 
Len Baker 
Len Barber 
Leon Barnett 
Leonard Barry 
Les Barrell 
Les Barrett 
Leslie Balcombe 
Lewis Baker 
Lewis Ballham 
Luke Ayling 
Malcolm Bailey 
Malcolm Bailey 
Malcolm Barrass 
Mark Bailey 
Mark Barham 
Mark Barnard 
Martin Bakes 
Martin Barlow 
Mat Bailey 
Matt Baker 
Matt Barrass 
Matthew Barnes-Homer 
Matty Barlow 
Michael Bakare 
Michael Barnes 
Michael Barron 
Mickey Barker 
Mike Bailey 
Mike Balson 
Mike Bamber 
Mike Barnard 
Mike Barrett 
Mike Barry 
Moses Barnett 
Nathan Baker 
Ned Barkas 
Neil Austin 
Neil Bailey 
Neil Banfield 
Neil Barrett 
Neville Bannister 
Nick Awford 
Nick Barmby 
Nicky Bailey 
Nicky Banger 
Ollie Banks 
Paddy Atkinson 
Pat Baldwin 
Patrick Bamford 
Paul Atkinson 
Paul Atkinson 
Paul Bacon 
Paul Baines 
Paul Baker 
Paul Bannister 
Paul Barnes 
Paul Barrett 
Paul Barron 
Paul Barrowcliff 
Percy Austin 
Peter Baah 
Peter Baker 
Peter Baker 
Peter Barlow 
Peter Barnes 
Phil Barber 
Phil Bardsley 
Phil Barlow 
Phil Bach 
Ralph Banks 
Ray Barlow 
Ray Barnard 
Raymond Bailey 
Reg Attwell 
Reg Baines 
Richard Baird 
Richard Barroilhet 
Richard Barker 
Richie Baker 
Richie Barker 
Richie Barker 
Rikki Bains 
Rob Atkinson 
Robert Barker 
Rocky Baptiste 
Roland Bartholomew 
Ron Atkinson 
Ron Barnes 
Ronald Baird 
Ronnie Bacon 
Ross Barkley 
Roy Bailey 
Roy Baines 
Roy Baker 
Ryan Auger 
Ryan Austin 
Ryan Baldacchino 
Sam Baddeley 
Sam Bagnall 
Sam Baldock 
Sam Barkas 
Sam Barnes 
Scott Barrett 
Scott Barron 
Septimus Atterbury 
Shabazz Baidoo 
Shaun Barker 
Simon Baldry 
Simon Barker 
Stefan Bailey 
Steve Aylott 
Steve Baines 
Steve Baker 
Steve Baker 
Steve Ball 
Steve Ball 
Steve Banks 
Steve Barnes 
Stewart Barrowclough 
Stuart Barfoot 
Stuart Barlow 
Ted Ballard 
Terry Austin 
Terry Bailey 
Terry Baker 
Thomas Bagley 
Tom Baddeley 
Tom Bailey 
Tom Bamford 
Tom Barkhuizen 
Tom Barlow 
Tom Barnett 
Tom Barrett 
Tommy Baldwin 
Tommy Ball 
Tommy Banks 
Tommy Barber 
Tony Barras 
Tony Barratt 
Tosh Barrell 
Trevor Atkinson 
Trevor Aylott 
Trevor Bailey 
Tunji Banjo 
Tyrone Barnett 
Wally Barnard 
Walter Atkinson 
Walter Aveyard 
Will Atkinson 
William Bagley 
William Baker 
William Ball 
William Banks 
LGBT rights in Africa 
Infobox 
InfoboxImage 
DecreasePositive 
As of 
Start date 
MONTHNAME 
DMCA 
Dated maintenance category 
Cite journal 
FULLROOTPAGENAME 
Ns has subpages 
Infobox 
Population Matters 
Sokoto Caliphate 
Pages with missing files 
Refbegin 
Refend 
Ebola 
ICD10 
Bochotnica 
Augustus 
Julius Caesar 
Convert 
Convert 
Convert/text 
Geography of Nigeria 
Moscow 
Saint Petersburg 
Cities and towns in Russia 
Geology 
Russia 
Novosibirsk 
Yekaterinburg 
Pencil 
Ballpoint pen 
Pencil sharpener 
Bread 
Handicraft 
Production 
Sound 
Technical pen 
Abuja 
11 
12 
13 
14 
15 
16 
17 
18 
19 
21 
22 
23 
24 
25 
26 
27 
28 
29 
31 
32 
33 
34 
35 
36 
37 
38 
39 
41 
42 
43 
Edmond Debeaumarché 
Conductive ink 
Bermuda Triangle 
Sahara 
Mecca 
Medina 
44 
45 
46 
47 
48 
49 
50 
51 
52 
53 
54 
55 
56 
57 
58 
59 
60 
61 
62 
63 
64 
65 
66 
67 
68 
69 
70 
71 
72 
73 
74 
75 
76 
77 
78 
79 
A 
Be 
Ve 
Ge 
De 
Ye 
Yo 
Zhe 
Ze 
I 
Short I 
Ka 
El 
Em 
En 
O 
Pe 
Er 
Es 
Te 
U 
Ef 
Kha 
Tse 
Che 
Sha 
Shcha 
Soft sign 
Yery 
Hard sign 
E 
Yu 
Ya 
Arabs 
80 
81 
82 
83 
84 
85 
86 
87 
Sun 
Nizhny Novgorod 
Football 
VietJet Air 
Pacific Airlines 
Airbus 
Housefly 
Compton 
Abbe 
Abbot 
Satellite 
Moon 
Planet 
Americas 
Abetti 
Abul Wafa 
Abulfeda 
Radio France Internationale 
China Radio International 
1 
2 
4 
News Agency of Nigeria 
Nolisair 
Abuja National Mosque 
Lagos 
Lagos 
Tqi 
Warsaw 
Azare 
Arguments 
TableTools 
Diarrhea 
Malaria 
Hepatitis A 
Malnutrition 
Pit latrine 
Georgia 
Bell pepper 
Asian Month 
Gwanki 
Arabic 
Agriculture 
Valparaíso 
Imelda Marcos 
Adekunle Gold 
Lil Kesh 
Funmi Aragbaye 
Bola Are 
Segun Arinze 
Ayinde Barrister 
Charly Boy 
Christy Essien-Igbokwe 
Murasaki Shikibu 
Beautiful Nubia 
Gbenga Adeboye 
Keziah Jones 
Kokoro 
Maud Meyer 
Evi Edna Ogholi 
Tosin Jegede 
Tunji Oyelana 
Yemi Alade 
Peru 
Argentina 
Michael Jackson 
Janet Jackson 
Aretha Franklin 
Bessie Smith 
Prince 
Frank Sinatra 
B.B. King 
Ray Charles 
Chubby Checker 
Bob Dylan 
Janis Joplin 
Ecuador 
Willie Nelson 
Roberta Flack 
Andy Allo 
Obadiah Johnson 
Orisadipe Obasa 
Richard Akinwande Savage 
Babatunde Kwaku Adadevoh 
Science and technology 
English language 
Muhammad al-Bukhari 
Will Smith 
Prague 
Teresa Teng 
SpesBona 
Pages using invalid self-closed HTML tags 
Hidden categories 
Huell Howser 
Marian Anderson 
Tina Turner 
Democracy 
European Union 
Tuberculosis 
HIV/AIDS 
Joe Dassin 
Johnny Hallyday 
Claude François 
Brazil 
Brazil 
Coronel Fabriciano 
Frances Ames 
Fatima Massaquoi 
Funmilayo Ransome-Kuti 
Paris 
France 
Lyon 
Toulouse 
Elnathan John 
Abubakar Adam Ibrahim 
Germany 
Madrid 
Jean Lassalle 
Philippe Poutou 
Beijing 
Ottawa 
Daura 
Šiprage 
Nickelodeon 
Five Below 
Islamabad 
Roubaix 
EWTN 
Bilal Philips 
Baskin-Robbins 
Bosnia and Herzegovina 
User pt 
User es 
User gl 
User mwl 
User fr 
User it 
User an 
User oc 
User no 
User bn 
User hi 
User yue 
User zh-Hant 
User de-AT 
User bs 
User csb 
User dsb 
User hr 
User hsb 
User kg 
User la 
User ro 
User ru 
User sc 
User sh 
User sk 
User sr 
User lv 
User nl 
User ab 
User rn 
User zh 
User lzh 
User eo 
User ko 
User is 
User li 
User tg 
User fa 
User ur 
User ps 
User ta 
User en-GB 
User si 
User zu 
User ig 
User sv 
User nn 
User nds 
User mg 
User zh-Hans 
User ja 
User lt 
User hu 
Boko Haram insurgency 
Refugee 
Dalori 
User pl 
User or 
User pi 
User kn 
User eu 
Chile 
User fi 
User et 
User grc 
User nb 
User ka 
User sco 
User pih 
User nov 
Corbin Bleu 
Airport 
Gaya, Nigeria 
Otto Heinrich Warburg 
Taipei 
Somalia 
Protestantism 
Emil Warburg 
Soviet Union 
Montpellier 
Bordeaux 
Nantes 
Rennes 
Marseille 
Gottfried Wilhelm Leibniz 
Lucero 
Isaac Newton 
Syriac language 
Johannes Kepler 
Euclid 
Johann Sebastian Bach 
Music 
Leonhard Euler 
Archimedes 
Leonardo da Vinci 
Michelangelo 
Raphael 
Lucas Cranach the Elder 
Strasbourg 
Lists of communes of France 
Kilishi 
Dawakin Kudu 
Blaise Pascal 
Namibia 
Lille 
Grenoble 
Comoros 
Lung cancer 
Kano 
Kano State 
States of Nigeria 
Imo State 
Kwara 
Lagos 
Katsina 
Kebbi State 
Sokoto State 
Borno State 
Cities in Nigeria 
Gombe 
Gombe State 
Adamawa State 
Taraba State 
Aliko Dangote 
Nigerian writers 
Writers 
Kaduna 
German people 
South African politicians 
Politicians 
Countries in Africa 
Owerri 
Port Harcourt 
Onitsha 
Benin City 
Warri 
Aba, Abia 
Rabiu Kwankwaso 
Nigerian politicians 
Akwa Ibom State 
Rivers State 
Greek mathematicians 
Greek people 
Mathematicians 
German philosophers 
Philosophers 
Søren Kierkegaard 
Bar Sargis 
Rome 
Cities and towns in Italy 
Cities in Europe 
Cities in Africa 
Naples 
Milan 
Cairo 
Cities in Egypt 
Addis Ababa 
Nairobi 
Cities in Kenya 
Dakar 
Kampala 
Uganda 
Jeremiah Gyang 
French politicians 
Cities in France 
New York City 
Google AdSense 
Carl's Jr. 
House 
Abia State 
Enugu 
Enugu State 
Cross River State 
Calabar 
Enugu 
Jigawa State 
Yobe State 
Barcelona 
Jakarta 
Cities in Indonesia 
Cities in Asia 
Countries in Asia 
Countries 
Manila 
Hanoi 
Doha 
Qatar 
New Delhi 
Cities and towns in India 
Mumbai 
Chennai 
Kolkata 
Cities in Peru 
Cities in the Americas 
Americas 
Peru 
Countries in the Americas 
Brasília 
Cities in Brazil 
Salvador, Bahia 
Maradi, Niger 
Niamey 
Sokoto 
Ibadan 
Jos 
Ilorin 
List of Nigerian cities by population 
P-Square 
Nigerian musical groups 
Greek physicists 
Swiss mathematicians 
Swiss people 
Swiss physicists 
German painters 
Painters 
Tomato 
Onion 
Vegetables 
Bayero University Kano 
Universities and colleges in Nigeria 
Universities and colleges 
Knowledge 
University of Oxford 
Universities in the United Kingdom 
Elderson Echiéjilé 
John Obi Mikel 
Meat 
Ogenyi Onazi 
Ahmed Musa 
Layal Abboud 
Vincent Enyeama 
Riyad Mahrez 
Algeria 
Oceania 
Conakry 
Djibouti 
Djibouti 
Djibouti 
Brazzaville 
Trianthema portulacastrum 
Kinshasa 
Lubumbashi 
Mbuji-Mayi 
Bukavu 
Kananga 
Bratislava 
Cities and towns in Slovakia 
Kuala Lumpur 
Canada 
Montreal 
Calgary 
Toronto 
Edmonton 
Vancouver 
Mississauga 
Winnipeg 
Rashidi Yekini 
Nwankwo Kanu 
Victor Ikpeba 
Emmanuel Amunike 
Ivory Coast 
Abidjan 
Luanda 
Khartoum 
Cape Town 
Johannesburg 
Lagos State 
Ogun State 
Ondo State 
Osun State 
Ondo 
Durban 
Pretoria 
Mogadishu 
Accra 
Dar es Salaam 
Sports 
Leon Balogun 
Goodluck Jonathan 
Donald Trump 
Ahmadu Bello University 
Ibrahim Zakzaky 
Sanusi Lamido Sanusi 
Abubakar Tafawa Balewa 
Segun Odegbami 
Yakubu 
Maradun 
Ralphie May 
Aminu Kano 
Cup 
Drink 
Tea 
God 
Quran 
Mosque 
Bauchi 
Bosnia and Herzegovina 
Spain 
Zazzau 
Belarus 
Carles Puigdemont 
Spanish politicians 
Mariano Rajoy 
Emmanuel Macron 
Jacques Chirac 
François Mitterrand 
François Hollande 
British politicians 
Theresa May 
David Cameron 
Tony Blair 
Nnamdi Azikiwe 
Johnson Aguiyi-Ironsi 
José Luis Rodríguez Zapatero 
José María Aznar 
François Fillon 
Lionel Jospin 
Alain Juppé 
Jean-Pierre Raffarin 
Gordon Brown 
John Major 
Dominique de Villepin 
Jean-Marc Ayrault 
Manuel Valls 
Bernard Cazeneuve 
Édouard Philippe 
Sari Abacha 
Shehu Abdullahi 
George Abbey 
Catalonia 
Olubayo Adefemi 
Kelechi Iheanacho 
Alex Iwobi 
Odion Ighalo 
Moses Simon 
Wilfred Ndidi 
Peter Etebo 
John Ogu 
Daniel Akpeyi 
William Troost-Ekong 
Yakubu Gowon 
Murtala Mohammed 
Olusegun Obasanjo 
Shehu Shagari 
Plateau State 
Nasarawa State 
Sani Abacha 
Abdulsalami Abubakar 
Ernest Shonekan 
Nicolas Sarkozy 
Pierre Messmer 
Raymond Barre 
Pierre Mauroy 
Laurent Fabius 
Michel Rocard 
Édith Cresson 
Jay-Jay Okocha 
Daniel Amokachi 
Asuquo Ekpe 
Julius Aghahowa 
Carl Ikeme 
Nosa Igiebor 
Aaron Samuel Olanare 
Emmanuel Emenike 
Sunday Mba 
Victor Moses 
Brown Ideye 
Ibrahim Shekarau 
Abdullahi Umar Ganduje 
Nasir Ahmad el-Rufai 
Mukhtar Ramalan Yero 
Patrick Ibrahim Yakowa 
Alderney 
Namadi Sambo 
Ahmed Makarfi 
Yemi Osinbajo 
Abba Kyari 
Naypyidaw 
Yangon 
Vienna 
Cities and towns in Austria 
Zainab Ahmed 
Yaoundé 
Maroua 
Garoua 
Douala 
Goat 
Los Angeles 
Quebec 
Leonard Cohen 
Cities and towns in Lebanon 
Lebanon 
Papua New Guinea 
Kogi State 
Alexandria 
Casablanca 
Rabat 
Cities in Morocco 
Morocco 
Italian people 
Gabon 
Equatorial Guinea 
Eritrea 
The Gambia 
Bamako 
Cities in Mali 
Mali 
Banjul 
Kader Amadou 
Karim Lancina 
Kassaly Daouda 
Vincent Aboubakar 
Nicolas Nkoulou 
Cameroonian people 
Fabrice Ondoa 
Benjamin Moukandjo 
Georges Mandjeck 
N'Djamena 
Moundou 
Niger River 
River 
Niger State 
Sokoto River 
Diffa 
Helsinki 
Cities and towns in Finland 
Stockholm 
Cities in Sweden 
Emmerson Mnangagwa 
Robert Mugabe 
Zimbabwe 
Zimbabwe 
Zambia 
Harare 
Lusaka 
Zambia 
Ghana 
Corsica 
Sardinia 
Sicily 
Mallorca 
Palma de Mallorca 
Cagliari 
Palermo 
Turin 
New Guinea 
Borneo 
Brunei 
Java 
Sumatra 
Sulawesi 
Surabaya 
Bandung 
Bekasi 
Medan 
Banjarmasin 
Honshu 
Japan 
Hokkaido 
Kyushu 
Shikoku 
Chongqing 
Shanghai 
Guangzhou 
Hangzhou 
Chengdu 
Wuhan 
Valencia 
Seville 
Málaga 
Bilbao 
Zaragoza 
Granada 
London 
Manchester 
Birmingham 
Liverpool 
Glasgow 
Bristol 
Nottingham 
Southampton 
Newcastle upon Tyne 
Leeds 
Portsmouth 
Leicester 
Hamburg 
Munich 
Cologne 
Frankfurt 
Düsseldorf 
Stuttgart 
Essen 
Dortmund 
Leipzig 
Bremen 
Dresden 
Hanover 
Nuremberg 
Duisburg 
Xi'an 
Tianjin 
Jinan 
Shenzhen 
Jean d'Ormesson 
French writers 
University of Maiduguri 
List of heads of state of Niger 
List of heads of state of Chad 
List of presidents of Cameroon 
List of presidents of Togo 
Knowledge 
Hamani Diori 
Seyni Kountché 
Ali Saibou 
Mahamane Ousmane 
Gaborone 
Cities in Botswana 
Botswana 
Windhoek 
Cities in Namibia 
Namibia 
Maseru 
Asmara 
Kigali 
Cities in Rwanda 
Rwanda 
Hargeisa 
Praia 
Lilongwe 
Malawi 
Malawi 
Welcome 
George W. Bush 
Mexico 
Kwara State 
Ekiti State 
Mamadou Tandja 
Houston 
San Francisco 
Chicago 
Phoenix, Arizona 
Philadelphia 
San Antonio 
Yamoussoukro 
Balaraba Ramat Yakubu 
List of Governors of Kano State 
River delta 
Rothschild family 
Tino Insana 
Delta State 
Ifeanyi Okowa 
Edo State 
Akinwunmi Ambode 
Babatunde Fashola 
Bola Tinubu 
Cricket 
Atiku Abubakar 
Wolfgang Amadeus Mozart 
James Ibori 
Mark Zuckerberg 
Sildenafil 
Costa Rica 
Riga 
Cities in Latvia 
Mexico 
Ludwig van Beethoven 
Richard Wagner 
Dieterich Buxtehude 
Jean-Philippe Rameau 
List of Governors of Lagos State 
Aminu Tambuwal 
Larry Page 
Aminu Isa Kontagora 
Nigerian military personnel 
Dominic Oneya 
Mohammed Buba Marwa 
Olagunsoye Oyinlola 
Bangkok 
Asaba, Delta 
Ummarun Dallaje 
Gusau 
Dutse 
Muhammadu Dikko 
Tahoua 
Jimmy Wales 
Clomifene 
Ibrahim Babangida 
Separated entries 
List 
PAGENAMEBASE 
String 
Trauenbaum 
Abubakar Gumi 
Chika Unigwe 
Chinua Achebe 
Boston 
Austin, Texas 
Columbus, Ohio 
Seattle 
Mexico City 
Ali Nuhu 
Rice 
Orgulho e Paixão 
Ouagadougou 
Bobo-Dioulasso 
Alassane Ouattara 
Roch Marc Christian Kaboré 
Mahamadou Issoufou 
Karachi 
Lahore 
Billy Graham 
Pope Benedict XVI 
Popes 
Pope John Paul II 
Pope Francis 
Gombe State University 
Justin Trudeau 
Islam in Nigeria 
Sunday 
Rabbit 
Kanuri language 
Margi language 
Fula people 
Giwa 
Ammarpad 
Prophet 
Solid 
Liberia 
March 
April 
May 
June 
July 
August 
September 
October 
November 
December 
January 
February 
Month header 
Monday 
Tuesday 
Wednesday 
Thursday 
Friday 
Saturday 
Television 
Kaduna River 
2018 
Bangalore 
Hyderabad 
Surat 
Ahmedabad 
Years 
Airports 
List of airports in Nigeria 
Jaipur 
Kanpur 
Lucknow 
Ghaziabad 
Agra 
Pune 
Nile 
Istanbul 
Farooq Kperogi 
Nagpur 
Visakhapatnam 
Indore 
Thane 
Kurfi 
Rémi Mathis 
Bank 
Saddam Hussein 
Carlos Kameni 
Sa'adu Abubakar 
Samuel Eto'o 
Laurent Gbagbo 
Robert Guéï 
NneNne Iwuji-Eme 
Xi Jinping 
History 
Avicenna 
Maher Zain 
Sunnah 
Omar 
Anas1712 
Yakubu Muhammed 
Birni-N'Konni 
Zinder 
Stephen Hawking 
Rashidun Caliphate 
Mohamed Salah 
List of radio stations in Nigeria 
Isyaku Rabiu 
Martin Wait 
Jiang Zemin 
Hu Jintao 
Valéry Giscard d'Estaing 
Georges Pompidou 
Kano Emirate 
Morocco 
Ondo City 
Akure 
Caracas 
Fasting in Islam 
Muslims 
Ja'afar Mahmud Adam 
Central Africa 
Taj Mahal 
Burj Khalifa 
Buildings and structures in the United Arab Emirates 
United Arab Emirates 
Buildings and structures 
Sadiq Khan 
Mayors of London 
Anne Hidalgo 
Mayors of Paris 
Mayors 
Bill de Blasio 
Mayors of New York City 
Patricia de Lille 
Mayors of Cape Town 
Bashir Tofa 
Shia Islam 
Madagascar 
Antananarivo 
Kumasi 
Hooded vulture 
Francolin 
White-rumped seedeater 
Great egret 
Pink-backed pelican 
Squacco heron 
Black-crowned night heron 
Western swamphen 
Black-winged stilt 
Fasting 
Benue 
Benue State 
Benue River 
Yola, Adamawa 
Bagwai 
Makurdi 
Atom 
Science 
List of rulers of Kano 
Paradise 
Saint Lucia 
Anambra State 
Awka 
Umuahia 
Durbar festival 
Bayelsa State 
Wikidata list 
Napoleon 
Maitama Sule University, Kano 
Maitama Sule 
2018 FIFA World Cup 
Nikah mut'ah 
Ankara 
İzmir 
Bursa 
Adana 
Gaziantep 
Konya 
Antalya 
Kayseri 
Mersin 
BBC Hausa 
Cities in Iran 
Tehran 
Mashhad 
Isfahan 
Qom 
Edirne 
Talk pages 
Northern Region, Nigeria 
Karaj 
Shiraz 
Tabriz 
Ahvaz 
Reply to 
Hans Christian Andersen 
Five pillars 
Chiang Mai 
Nakhon Ratchasima 
Ho Chi Minh City 
Haiphong 
Da Nang 
Cần Thơ 
Biên Hòa 
Nha Trang 
Liu Xiaobo 
Monte Águila 
Seoul 
Busan 
Incheon 
Daegu 
Daejeon 
Zaynab Alkali 
Encyclopedia 
Mansa Musa 
Abubakar Shekau 
Somaliland 
Salem Al Ketbi 
History of Mali 
History by country 
Mallam Aminu Kano International Airport 
Tokyo 
Cities in Japan 
Yokohama 
Osaka 
Nagoya 
Airports in Nigeria 
Audu Bako 
Rabilu Musa 
Xcas 
Tukur Yusuf Buratai 
Sydney 
Melbourne 
Brisbane 
Perth 
Adelaide 
Rembrandt 
Elizabeth I 
Dangote Group 
Diego Velázquez 
Hammurabi 
Cyrus the Great 
Qin Shi Huang 
Claude Monet 
Vincent van Gogh 
Dmitri Mendeleev 
Attila 
Jacques Cartier 
Frédéric Chopin 
Laozi 
James Joyce 
Karl Marx 
Pablo Picasso 
Pythagoras 
Colombia 
Amazon River 
Athens 
Hadith 
Nawal al-Hawsawi 
Saudi Arabia 
Gold Coast, Queensland 
Philosophy 
Politics 
Dosso, Niger 
Birnin Kebbi 
Dogondoutchi 
Bamboo Airways 
Al-Masjid an-Nabawi 
Arnaud Beltrame 
Chiang Kai-shek 
Kaaba 
Tunisia 
Damaturu 
Baháʼí Faith 
Algaita 
Muharram 
Safar 
Rabiʽ al-Awwal 
Rabiʽ al-Thani 
Jumada al-awwal 
Jumada al-Thani 
Keffi 
List of newspapers in Nigeria 
Rajab 
Sha'ban 
Palestine 
Salvador Dalí 
English footballers 
Pakistani footballers 
Association football players by nationality 
Association football 
Cameroonian footballers 
Mandiraja, Banjarnegara 
Abeokuta 
Osogbo 
Minna 
Monrovia 
Mombasa 
Ramadan 
Shawwal 
Cotonou 
Porto-Novo 
Bukola Saraki 
Ebonyi State 
Abakaliki 
Max Air 
Oyo State 
Oyo, Oyo 
Henri Konan Bédié 
Félix Houphouët-Boigny 
Gao 
Faidherbia 
Senegalia senegal 
Vachellia nilotica 
Jaynagar Majilpur 
Nigerian footballers 
Ten simple rules for editing Wikipedia 
Your first article 
Copyright 
Neutral point of view 
Lisbon 
Cities in Portugal 
Portugal 
Offenbach am Main 
Verifiability 
Cheatsheet 
Trinidad and Tobago 
Yesno 
Tutorial 
Tutorial /Editing 
Tutorial /Wrap-up and more info 
Clear 
Tutorial /Registration 
Tutorial /Talk pages 
Tutorial /Wikipedia links 
Tutorial /Citing sources 
VisualEditor 
South Sudan 
Eswatini 
Lesotho 
Mbabane 
Eswatini 
Republic of the Congo 
Central African Republic 
Islands of Indonesia 
Islands 
Libreville 
Turkish Armed Forces 
Nnamdi Azikiwe International Airport 
Kaduna Book and Arts Festival 
Kadaria Ahmed 
Yoruba language 
Kaduna International Airport 
Igbo language 
French language 
Fela Kuti 
Alhassan Dantata 
Matthew Hassan Kukah 
Chinese language 
Latin 
Malcolm X 
Date 
Spoon 
States of Nigeria 
Hausa 
Nupe people 
Tel Aviv 
Ahmed Lawan 
John Onaiyekan 
Nigerian naira 
Access Bank Group 
Julius Berger 
Mozambique 
Maputo 
Mozambique 
Zangon Kataf 
Gbagyi people 
Yahaya Bello 
Bura language 
Biu, Nigeria 
Aminu Ibrahim Daurawa 
Idris Legbo Kutigi 
Rwanda 
Paul Biya 
Ahmadou Ahidjo 
Kaduna State University 
Nigerian Defence Academy 
Sahle-Work Zewde 
Ethiopia 
Book 
Education 
Economy 
Ibrahim Abubakar Njodi 
Maguzawa Hausa people 
Animal husbandry 
Milk 
Lake Chad 
Ado Bayero 
Shehu Idris 
Ireland 
Stephen Harper 
Paul Martin 
Jean Chrétien 
Kim Campbell 
Usman dan Fodio 
Hausa language 
Maiduguri International Airport 
Murtala Muhammed International Airport 
Company 
Industry 
Oando 
Larry Sanger 
Bujumbura 
Cities in Burundi 
Computer 
Door 
Window 
Room 
Bed 
Egyptians 
Bangui 
São Tomé and Príncipe 
Central African Republic 
Jamilu Collins 
Ola Aina 
Isaac Success 
Henry Onyekuru 
Abu Bakr 
Shahid 
Uthman 
Ali 
Abdulmumini Kabir Usman 
Jalingo 
Sweet potato 
Askira/Uba 
Canberra 
Week 
Potiskum 
Asian Development Bank 
Jair Bolsonaro 
World Bank 
Year 
Brazilian politicians 
Brazilian people 
Recep Tayyip Erdoğan 
Shinzo Abe 
World War II 
Aminu Bello Masari 
Yenagoa 
Japanese language 
Muammar Gaddafi 
Wikipedia Asian Month/2018 
Mikel Agu 
Ikouwem Udo 
Tyronne Ebuehi 
Dele Ajiboye 
University of Ilorin 
Abdulfatah Ahmed 
Palm Islands 
Muhammadu Kabir Usman 
Malik ibn Anas 
Madhhab 
Akihito 
Abdulla Yameen 
Mahatma Gandhi 
Sunday Faleye 
Teslim Fatusi 
Dejo Fayemi 
Peter Fregene 
Reuben Gabriel 
Mohammed Gambo 
Ahmed Garba 
Celestine Babayaro 
Rabiu Baita 
Abubakar Balarabe 
Sunday Chibuike 
John Chiedozie 
Punjabi language 
Punjabis 
Mahathir Mohamad 
Tanzania 
C. Odumegwu Ojukwu 
Eid al-Adha 
Eid al-Fitr 
Maliki 
Ajibade Babalade 
Oladipupo Babalola 
David Adekola 
Sam Ayorinde 
Ramon Azeez 
Reuben Agboola 
Dele Aiyenugba 
Joseph Akpala 
Kunu 
Millet 
Fura 
Woman 
Male gender 
Salt 
Margi 
Kwaya Kusar 
Bayo, Nigeria 
Tawhid 
Faith 
Igala people 
Ebira people 
Lokoja 
Olusola Saraki 
Abiola Ajimobi 
Shafiʽi school 
West Africa 
Nana Akufo-Addo 
Umaru Tanko Al-Makura 
Brian Idowu 
Victor Osimhen 
Francis Uzoho 
Daniel Itodo 
Kelechi Nwakali 
Uche Henry Agbo 
Dayo Ojo 
Abdullahi Ibrahim Alhassan 
Al-Shafiʽi 
Ahmad ibn Hanbal 
Hanbali 
Hanafi 
Abu Hanifa 
Osas Idehen 
Haruna Ilerika 
Kadiri Ikhana 
Pius Ikedia 
Ekigho Ehiosun 
Austin Ejide 
Henry Ekubo 
Friday Elahor 
Kanem–Bornu Empire 
Lakes 
Efan Ekoku 
Chijioke Ejiogu 
Eric Ejiofor 
Gbenga Arokoyo 
Emmanuel Ariwachukwu 
Victor Anichebe 
Kashim Ibrahim 
Elizabeth II 
Borno Emirate 
Ibn Khaldun 
Albert Einstein 
Mauritius 
Port Louis 
Nok 
Nok culture 
Sierra Leone 
Jaffa 
Jeddah 
Riyadh 
Abu Kabir 
Rumi 
Abraham 
Cities in Saudi Arabia 
Ranil Wickremesinghe 
Chandrika Kumaratunga 
Beirut 
Chisom Chikatara 
George Datoru 
Imadu Dooyum 
Tosin Dosunmu 
Kingsley Eduwo 
Jamiu Alimi 
Izala Society 
Adam A Zango 
Leotis Boateng 
Baldwin Bazuaye 
Yaro Bature 
Waidi Akanni 
Murphy Akanji 
Alloysius Agu 
Dutsin-Ma 
Modibo Adama 
Moses 
Prophets and messengers in Islam 
Karekare 
Revelation 
Muhammad ibn Musa al-Khwarizmi 
Pacific War 
Mohammed Ali Ndume 
Hasan ibn Ali 
Husayn ibn Ali 
Theater 
Ibn Battuta 
Al-Ghazali 
Al-Nawawi 
Abbasid Caliphate 
Shahada 
Five Pillars of Islam 
Salah 
Wudu 
As-salamu alaykum 
Old Testament 
New Testament 
Hakeem Olajuwon 
Kano Pillars F.C. 
Enyimba F.C. 
Mohammed Danjuma Goje 
Shehu Sani 
Central Bank of Nigeria 
Central bank 
Money 
Basket 
Metal 
Gidan Rumfa 
Muhammad Rumfa 
Marketplace 
Gani Fawehinmi 
Attahiru Jega 
Mahmood Yakubu 
Amina Zakari 
Aisha Buhari 
Abraham Lincoln 
Christians 
Alexander Lukashenko 
Abdulkadir Balarabe Musa 
Sabon Gari, Kaduna 
Birnin Gwari 
Chikun 
Kaduna North 
Kaduna South 
Igabi 
Ikara 
Zangon Kataf 
Jaba, Kaduna 
Kagarko 
Kajuru 
Faskari 
Jema'a 
Soba, Kaduna 
Kachia 
Sanga, Kaduna 
Makarfi 
Lere, Kaduna 
Kudan, Kaduna 
Kubau 
Kaura, Kaduna 
Kauru 
Bakori 
Batsari 
Dan Musa 
Funtua 
Kankia 
Malumfashi 
Mai'Adua 
Kankara 
Ingawa 
Kaita, Nigeria 
Mashi 
Rimi, Nigeria 
Musawa 
Mani, Nigeria 
Safana 
Matazu 
Sabuwa 
Jibia 
Bindawa 
Kashim Shettima 
Ali Modu Sheriff 
List of Governors of Borno State 
Mohammed Abdullahi Abubakar 
Babagana Monguno 
Suleiman Abba 
Sule Lamido 
Darius Ishaku 
Aisha Alhassan 
Samuel Ortom 
Bukar Ibrahim 
Karekare language 
Khadija Bukar Abba Ibrahim 
Rochas Okorocha 
Yusufari 
Nguru, Nigeria 
Fika, Nigeria 
Fune 
Yunusari 
Geidam 
Jakusko 
Karasuwa 
Gujba 
Machina, Nigeria 
Gulani 
Nangere 
Bade, Nigeria 
Bursari 
Tarmuwa 
Bama, Borno 
Abadam 
Baga, Borno 
Shani, Nigeria 
Chibok 
Damboa 
Dikwa 
Gwoza 
Guzamala 
Gubio 
Hawul 
Jere, Borno 
Kaga, Nigeria 
Konduga 
Kukawa 
Mafa 
Magumeri 
Marte, Borno 
Monguno 
Kala/Balge 
Mobbar 
Nganzai 
Tarauni 
Kumbotso 
Rimin Gado 
Albasu 
Madobi 
Shanono 
Bebeji 
Rano 
Bunkure 
Tofa, Nigeria 
Doguwa 
Tudun Wada 
Karaye 
Sumaila 
Wudil 
Takai 
Kiru, Nigeria 
Bichi 
Kabo, Nigeria 
Dawakin Tofa 
Kura, Nigeria 
Minjibir 
Gezawa 
Kibiya 
Garko, Nigeria 
Tsanyawa 
Gabasawa 
Ungogo 
Kunchi, Nigeria 
Makoda 
Garun Mallam 
Ajingi 
Warawa 
Fagge 
Gwale 
Dambatta 
Shah Rukh Khan 
Ikorodu 
Ikeja 
Uyo 
Asaba 
Bindo Jibrilla 
Yola North 
Yola South 
Local government areas of Nigeria 
Obafemi Awolowo 
Nigerians 
Agege 
Abaji 
Alimosho 
Ifako-Ijaiye 
Kosofe 
Mushin, Lagos 
Oshodi-Isolo 
Epe, Lagos 
Ibeju-Lekki 
Badagry 
Ojo, Lagos 
Amuwo-Odofin 
Somolu 
Apapa 
Eti-Osa 
Lagos Island 
Lagos Mainland 
Surulere 
Ajeromi-Ifelodun 
Wurno 
Binji 
Bodinga 
Dange Shuni 
Gada, Nigeria 
Goronyo 
Gudu 
Yabo, Nigeria 
Wamako 
Gwadabawa 
Illela, Nigeria 
Tureta 
Isa, Nigeria 
Kebbe 
Kware 
Rabah 
Sabon Birni 
Shagari, Nigeria 
Sokoto North 
Sokoto South 
Silame 
Tambuwal 
Tangaza 
Muslim ibn al-Hajjaj 
Auyo 
Babura 
Biriniwa 
Birnin Kudu 
Yankwashi 
Buji, Jigawa 
Gagarawa 
Garki, Jigawa 
Gumel 
Guri, Jigawa 
Gwaram 
Gwiwa 
Hadejia 
Jahun 
Kafin Hausa 
Kaugama 
Taura, Jigawa 
Sule Tankarkar 
Roni, Jigawa 
Ringim 
Miga, Jigawa 
Malam Madori 
Maigatari 
Kazaure 
Kiyawa 
Kiri Kasama 
Dandume 
Dutsi, Nigeria 
Batagarawa 
Baure, Nigeria 
Danja, Nigeria 
Charanchi 
Kafur, Nigeria 
Kusada 
Zango, Nigeria 
Sandamu 
Asa, Kwara 
Badaru Abubakar 
Ibrahim Hassan Dankwambo 
Simon Lalong 
Abubakar Sani Bello 
Baruten 
Pategi 
Edu, Kwara 
Ekiti, Kwara 
Ifelodun, Kwara 
Ilorin East 
Ilorin South 
Ilorin West 
Irepodun, Kwara 
Oke Ero 
Isin, Kwara 
Offa, Kwara 
Kaiama 
Moro, Kwara 
Oyun 
Demsa 
Toungo, Nigeria 
Fufore 
Ganye 
Girei 
Gombi 
Guyuk, Nigeria 
Hong, Nigeria 
Jada, Adamawa 
Lamurde 
Madagali 
Maiha 
Mayo Belwa 
Michika 
Mubi North 
Mubi South 
Numan, Nigeria 
Shelleng 
Song, Nigeria 
Okezie Ikpeazu 
Aba North 
Aba South 
Arochukwu 
Bende, Abia 
Ikwuano 
Isiala Ngwa North 
Isiala Ngwa South 
Isuikwuato 
Obi Ngwa 
Umu Nneochi 
Umuahia South 
Osisioma Ngwa 
Ohafia 
Umuahia North 
Ukwa West 
Ukwa East 
Ugwunagbo 
Ward 
Tafawa Balewa, Bauchi 
Dass, Nigeria 
Toro, Nigeria 
Bogoro 
Ningi, Nigeria 
Warji 
Ganjuwa 
Alkaleri 
Kirfi 
Darazo 
Misau 
Jama'are 
Shira, Nigeria 
Katagum 
Itas/Gadau 
Zaki, Nigeria 
Damban 
Gamawa 
Akko, Nigeria 
Balanga, Nigeria 
Billiri 
Dukku 
Funakaye 
Gombe, Gombe 
Kaltungo 
Kwami 
Nafada 
Shongom 
Yamaltu/Deba 
Abubakar Atiku Bagudu 
Aleiro 
Arewa Dandi 
Argungu 
Augie, Nigeria 
Bagudo 
Bunza 
Dandi, Nigeria 
Fakai 
Gwandu 
Jega, Nigeria 
Kalgo 
Koko/Besse 
Maiyama 
Ngaski 
Sakaba 
Shanga, Nigeria 
Suru, Nigeria 
Yauri, Nigeria 
Zuru 
Wasagu/Danko 
Abdul'aziz Abubakar Yari 
Anka, Nigeria 
Bakura, Nigeria 
Kaura Namoda 
Birnin Magaji/Kiyaw 
Bukkuyum 
Gummi, Nigeria 
Bungudu 
Maru, Nigeria 
Shinkafi 
Talata Mafara 
Chafe, Nigeria 
Zurmi 
Udom Gabriel Emmanuel 
Abak 
Eastern Obolo 
Eket 
Esit Eket 
Essien Udim 
Etim Ekpo 
Animal Farm 
Frederick Lugard, 1st Baron Lugard 
Tiv people 
Lake Malawi 
Swahili language 
Swahili people 
Agaie 
Agwara 
Wushishi 
Bida 
Borgu 
Bosso, Nigeria 
Chanchaga 
Edati 
Gbako 
2Baba 
Wizkid 
Gurara, Nigeria 
Katcha, Nigeria 
Kontagora 
Lapai 
Rafi, Nigeria 
Shiroro 
Suleja 
Tafa 
Agatu 
Gboko 
Katsina-Ala 
David Mark 
Otukpo 
Banky W. 
Attallah Shabazz 
Ilyasah Shabazz 
Abdulrahman Bello Dambazau 
Owoye Andrew Azazi 
Sambo Dasuki 
Dalhatu Tafida 
Martin Luther Agwai 
Diamond Bank 
Italian language 
Professor 
First Bank of Nigeria 
Surah 
Al-Fatiha 
Software 
Sheikh 
Football clubs in Nigeria 
Wood 
Energy 
Saud Al-Shuraim 
Imam 
Abdul-Rahman Al-Sudais 
Ado, Benue 
Apa, Nigeria 
Buruku 
Guma, Nigeria 
Konshisha 
Kwande 
Logo, Nigeria 
Obi, Nigeria 
Vandeikya 
Ushongo 
Ukum 
Tarka, Nigeria 
Ogbadibo 
Okpokwu 
Oju, Nigeria 
Ohimini 
Gwer East 
Gwer West 
Omuma 
Port Harcourt 
Obio-Akpor 
Tai, Rivers 
Bonny, Rivers 
Eleme, Rivers 
Emohua Town 
Luka Modrić 
Cristiano Ronaldo 
Antoine Griezmann 
Kylian Mbappé 
Raphaël Varane 
Bayajidda 
Baghdad 
Human penis 
Ogu–Bolo 
Aisha Lemu 
Ifeanyi Ugwuanyi 
Ike Ekweremadu 
Muiz ud din Bahram 
Rotimi Akeredolu 
Akoko North-East 
Akoko North-West 
Akoko South-East 
Akoko South-West 
Akure North 
Ose, Nigeria 
Owo 
Pontedera Airfield 
Akure South 
Ese Odo 
Idanre 
Ifedore 
Ilaje 
Ile Oluji/Okeigbo 
Irele 
Odigbo 
Okitipupa 
Ondo East 
Ondo West 
Aninri 
Awgu 
Enugu East 
Enugu North 
Enugu South 
Ezeagu 
Igbo Etiti 
Igbo Eze North 
Igbo Eze South 
Isi Uzo 
Nkanu East 
Nsukka 
Nkanu West 
Oji River 
Udenu 
Udi, Enugu 
Uzo Uwani 
Benedict Ayade 
Al-Suyuti 
Godwin Obaseki 
Okrika 
Gokana, Rivers 
Khana, Rivers 
Oyigbo 
Opobo–Nkoro 
Andoni 
Degema, Rivers 
Etche 
Ikwerre, Rivers 
Ogba–Egbema–Ndoni 
Ahoada East 
Ahoada West 
Abua–Odual 
Asari-Toru 
Akuku-Toru 
Ezenwo Nyesom Wike 
School House Corner 
Amsterdam 
Salaf 
Tabi'un 
Tabi' al-Tabi'in 
Ahlus Sunnah wal Jamaah 
Salafi movement 
Wahhabism 
Ibn Taymiyyah 
Sunni Islam 
Islamic schools and branches 
Sufism 
Hunter Island penguin 
David Woodard 
Teesdale, Victoria 
Battle of Peshawar 
Poisk 
Tawi River 
Lavun 
Rijau 
Magama, Nigeria 
Munya, Nigeria 
Mariga, Nigeria 
Mashegu 
Paikoro 
Mokwa 
Oredo 
Akoko Edo 
Egor 
Esan Central 
Esan North-East 
Esan South-East 
Esan West 
Etsako Central 
Etsako East 
Etsako West 
Igueben 
Ikpoba Okha 
Owan East 
Owan West 
Okpe 
Sapele, Delta 
Udu, Nigeria 
Uvwie 
Burutu 
Bomadi 
Warri North 
Warri South West 
Warri South 
Aniocha North 
Aniocha South 
Ethiope East 
Ethiope West 
Ika South 
Ika North East 
Ughelli North 
Ughelli South 
Oshimili South 
Oshimili North 
Ndokwa East 
Ndokwa West 
Isoko South 
Isoko North 
Patani, Delta 
Ibikunle Amosun 
Languages of Nigeria 
Guinea-Bissau 
Gboyega Oyetola 
Emmanuel Uduaghan 
Abeokuta North 
Abeokuta South 
Ifo 
Ijebu East 
Ijebu North 
Ijebu North East 
Ijebu Ode 
Lisa, Ogun 
Ikenne 
Sagamu 
Yewa North 
Yewa South 
Remo North 
Ewekoro 
Ado-Odo/Ota 
Ogun Waterside 
Odeda 
Odogbolu 
Obafemi Owode 
Ipokia 
Imeko Afon 
Aiyedaade 
Aiyedire 
Boripe 
Boluwaduro 
Egbedore 
Orolu 
Oriade 
Ejigbo 
Olorunda 
Ola Oluwa 
Odo Otin 
Obokun 
Ila, Osun 
Atakunmosa East 
Atakunmosa West 
Ede North 
Ede South 
Ife Central 
Ife East 
Ife North 
Ife South 
Ifedayo 
Ifelodun, Osun State 
Iwo, Osun 
Isokan 
Irewole 
Ilesa East 
Ilesa West 
Irepodun, Osun 
Etinan 
Ibeno 
Oron, Akwa Ibom 
Ika, Akwa Ibom 
Oruk Anam 
Ukanafun 
Urue-Offong/Oruko 
Uruan 
Udung-Uko 
Onna 
Okobo, Akwa Ibom 
Ibesikpo Asutan 
Ibiono-Ibom 
Ikono 
Ikot-Abasi 
Ikot Ekpene 
Obot-Akara 
Nsit-Ubium 
Nsit-Ibom 
Nsit-Atai 
Mkpat-Enin 
Mbo, Akwa Ibom 
Itu, Akwa Ibom 
Ini, Akwa Ibom 
Willie Obiano 
All Progressives Congress 
Dreams 
Henry Seriake Dickson 
Brass, Nigeria 
Ekeremor 
Kolokuma/Opokuma 
Nembe 
Ogbia 
Sagbama 
Southern Ijaw 
Akamkpa 
Akpabuyo 
Ogoja 
Menaggio 
El Mina, Mauritania 
Idi Amin 
Otto Detlev Creutzfeldt 
Zenith Bank 
Ziad Fazah 
Cities in Poland 
Poland 
Matthew Harris 
Dave Umahi 
Lilian Thuram 
Thierry Henry 
Marcel Desailly 
Hugo Lloris 
Olivier Giroud 
Patrick Vieira 
Didier Deschamps 
Laurent Blanc 
Michel d'Ornano 
Muhammad Abu Ali 
Bixente Lizarazu 
Sylvain Wiltord 
Michel Platini 
David Trezeguet 
Dhu al-Qadah 
Onicha 
Ohaukwu 
Ishielu 
Afikpo North 
Afikpo South 
Ebonyi, Ebonyi State 
Ezza North 
Ezza South 
Hausa Wikipedia 
Ikwo 
Ivo, Ebonyi 
Izzi 
Ohaozara 
Ozark Howler 
Kuli-kuli 
Orhionmwon 
Ovia North-East 
Ovia South-West 
Uhunmwonde 
Kayode Fayemi 
Ayo Fayose 
Ado Ekiti 
Ikere-Ekiti 
Oye, Ekiti 
Gbonyin 
Efon 
Ekiti East 
Ekiti South-West 
Ekiti West 
Emure 
Ido-Osi 
Ijero Ekiti 
Moba, Nigeria 
Ise/Orun 
Irepodun/Ifelodun 
Ilejemeje 
Ikole 
Ikeduru 
Aboh Mbaise 
Ahiazu Mbaise 
Ehime Mbano 
Ezinihitte Mbaise 
Ideato North 
Ideato South 
Ihitte/Uboma 
Isiala Mbano 
Isu, Nigeria 
Owerri West 
Mbaitoli 
Ngor Okpala 
Njaba 
Nkwerre 
Nwangele 
Obowo 
Oguta 
Owerri North 
Ohaji/Egbema 
Okigwe 
Onuimo 
Orlu, Imo 
Owerri Municipal 
Orsu 
Oru East 
Oru West 
Adavi, Nigeria 
Ajaokuta 
Ankpa 
Bassa, Kogi State 
Dekina 
Ibaji 
Idah 
Igalamela-Odolu 
Ijumu 
Kabba/Bunu 
Koton Karfe 
Mopa-Muro 
Ofu, Nigeria 
Ogori/Magongo 
Okehi 
Okene 
Olamaboro 
Omala, Nigeria 
Yagba East 
Yagba West 
Karu LGA 
Kokona 
Nasarawa, Nasarawa State 
Toto, Nigeria 
Akwanga 
Egon, Nigeria 
Wamba, Nigeria 
Doma, Nigeria 
Keana 
Lafia 
Obi, Nasarawa State 
Boss Mustapha 
Afijio 
Akinyele 
Egbeda 
Ido, Nigeria 
Kajola 
Irepo 
Baltzar von Platen 
Oju, Nigeria 
Lagelu, Oyo 
Atiba 
Atisbo 
Itesiwaju 
Ona Ara 
Ori Ire 
Orelope 
Iwajowa 
Ibadan North 
Ibadan North-East 
Ibadan North-West 
Ibadan South-West 
Ibadan South-East 
Ibarapa Central 
Ibarapa East 
Oluyole, Nigeria 
Ogo Oluwa 
Olorunsogo 
Oyo East 
Ibarapa North 
Surulere, Oyo State 
Ogbomosho North 
Ogbomosho South 
Oyo West 
Saki West 
Saki East 
Barkin Ladi 
Bassa, Plateau State 
Bokkos 
Jos East 
Jos North 
Jos South 
Wase, Nigeria 
Kanam, Nigeria 
Mangu, Nigeria 
Shendam 
Riyom 
Qua'an Pan 
Kanke, Nigeria 
Pankshin 
Langtang North 
Mikang 
Langtang South 
Ardo Kola 
Bali, Nigeria 
Donga, Nigeria 
Gashaka 
Gassol 
Ibi, Nigeria 
Karim Lamido 
Kurmi, Nigeria 
Lau, Nigeria 
Sardauna, Nigeria 
Takum 
Wukari 
Ussa 
Yorro 
Zing, Nigeria 
W. A. B. Coolidge 
Goma 
Goma 
U.S. state 
Sergio Ramos 
Sergio Busquets 
Jordi Alba 
Max Liedtke 
Marcus Rashford 
Dire Dawa 
Gondar 
Bahir Dar 
Manchester United F.C. 
Real Madrid CF 
FC Barcelona 
Samwel Mushai Kimani 
Arsenal F.C. 
Chelsea F.C. 
Manchester City F.C. 
Pelé 
Ronaldo 
Ronaldinho 
Diego Maradona 
Hawaii 
Washington, D.C. 
George Washington 
Liverpool F.C. 
Steven Gerrard 
Tillabéri Region 
Agadez Region 
Diffa Region 
Dosso Region 
Maradi Region 
Tahoua Region 
Zinder Region 
Ashanti Region 
Brong-Ahafo region 
Central Region 
Greater Accra Region 
Northern Region 
Upper East Region 
Upper West Region 
Volta Region 
Western Region 
Eastern Region 
Abubakar Adamu Mohammed 
Averroes 
Wyoming 
Wisconsin 
World War I 
Combatant 
José Mourinho 
Alabama 
Alaska 
Qurdarik-e Olya 
Mesut Özil 
HBM Iqbal 
Martin Luther King Jr. 
Hillary Clinton 
Arizona 
Arkansas 
Colorado 
California 
Nevada 
Muhammed Bello 
Islamic studies 
Ulama 
Ulama 
Neymar 
Lionel Messi 
Connecticut 
Delaware 
Matt Chang 
A 
Letter 
B 
C 
Keep 
Indiana 
Iowa 
D 
E 
F 
Cuba 
Haiti 
Jamaica 
Panama 
Port-au-Prince 
New York 
Florida 
New York 
Khans of Bollywood 
Paraguay 
Mario Abdo Benítez 
Asunción 
Bolivia 
Ohio 
Oklahoma 
Oregon 
Moshood Abiola 
Angelina Jolie 
Suleiman Othman Hunkuyi 
Rihanna 
New Mexico 
Texas 
Vermont 
Virginia 
Utah 
North Dakota 
South Dakota 
Nebraska 
Montana 
Ugandan politicians 
Ugandan people 
Muhammad Sani Abdullahi 
Tiger Woods 
Miamitown bridge collapse 
Herbert Copeland 
Fatima al-Fihri 
Hadiza Bala Usman 
Nigerian Ports Authority 
Vic Cockcroft 
Africaine 
Christian Gessner 
Paris Saint-Germain F.C. 
Xiangshan Global Studios 
Kindness 
Umar Farouk Abdulmutallab 
White House 
Official residence 
Head of state 
Madame Tussauds 
Gambo Sawaba 
Sergius VI of Naples 
A Holiday Album 
President of Nigeria 
Cage 
Mesh 
Cereal 
Grain 
Silo 
Rilwan Akiolu 
Oba 
Oba of Lagos 
Mohammed Yusuf 
King 
Queen regnant 
Paul Kagame 
Seychelles 
Indian Ocean 
Abdel Fattah el-Sisi 
Kafanchan 
Vasip Şahin 
Election 
Adh-Dhariyat 
2, The Cow, al-Baqarah 
Jae Deen 
Lady Gaga 
Hadiza Isma El-Rufai 
Montsoreau 
Idaho 
Illinois 
Chris Brown 
Georgia 
Kansas 
Muhammad Iqbal 
Ahmed Shawqi 
Kahlil Gibran 
Kentucky 
Louisiana 
Hajj 
CNN 
2019 
Charles, Prince of Wales 
Names of God in Islam 
Dino Melaye 
Maine 
Maine 
Maryland 
Massachusetts 
Michigan 
Minnesota 
Mississippi 
Missouri 
Ohio 
Mississippi 
Missouri 
Joseph Edet Akinwale Wey 
Kashmir 
Himalayas 
Iya Abubakar 
New Hampshire 
New Jersey 
South Carolina 
North Carolina 
Anne Hathaway 
University of Nigeria 
Pennsylvania 
Rhode Island 
Mansur Dan Ali 
Abu-Abdullah Adelabu 
Legume 
Fruit 
Kate Garvey 
Prime Minister of the United Kingdom 
Head of government 
Angela Merkel 
Tennessee 
Washington 
West Virginia 
Hejaz 
Shitta-Bey Mosque 
Eiffel Tower 
Champ de Mars 
Sundar Pichai 
Hausa-language cinema 
Hadiza Aliyu 
Aminu Saira 
Natasha Akpoti 
Nigerian musicians 
Bat 
Yusuf Datti Baba-Ahmed 
Parc des Princes 
Camp Nou 
Akanu Ibiam International Airport 
Key 
Vagina 
Marriage 
Husband 
Wife 
Divorce 
Edward Allen 
Mohammed Indimi 
Baku 
Terrorism 
Oslo 
Ice 
Kid Cudi 
Americans 
Rugby league 
Montgomery, Alabama 
Denver 
Honolulu 
Organ 
Tongue 
Ole Gunnar Solskjær 
Yusuf Barnabas Bala 
Matsuo Bashō 
Luca Zidane 
Time 
Sand 
Soil 
Bala Usman 
Fuat Oktay 
Abu Bakr Atiku 
Gidado dan Laima 
Ngazargamu 
Ali Gazi 
Nail 
Finger 
Arm 
Leg 
Gecko 
Star 
Soybean 
Mango 
Urine 
Feces 
Human feces 
Perspiration 
Wayne Rooney 
Asamoah Gyan 
Joseph-Antoine Bell 
Kazadi Mwamba 
Black Stone 
Masjid al-Haram 
Afakriya Gadzama 
Tawaf 
Umrah 
Dhaka 
Cities in Bangladesh 
Bangladesh 
Baoding 
Country 
Safa and Marwa 
Algiers 
Cities in Algeria 
Annaba 
Oran 
Wikipedia Asian Month/2019 
Uba Sani 
Surulere 
Languages of Nigeria 
Constantine, Algeria 
Blida 
Zamzam Well 
Adhan 
Tallahassee, Florida 
Miami 
Adamu Ciroma 
Bamanga Tukur 
Aminu Abdullahi Shagali 
Cape Verde 
Copenhagen 
Cities and towns in Denmark 
Denmark 
Henna 
Hadiza Sabuwa Balarabe 
Tijjani Yahaya Kaura 
Suleiman Abdu Kwari 
Mamman Nasir 
Callum Hudson-Odoi 
Notre-Dame de Paris 
Bello Mandiya 
Defecation 
Pliny the Elder 
Black hole 
Central Asia 
Çamlıca Mosque 
Turkish language 
Fard 
Hindustani language 
Tijjani Muhammad-Bande 
Richard Simmons 
Jonathan Banks 
Persepolis F.C. 
List of Nigerian states by population 
Collapsible list 
(( 
)) 
Hajji 
Thomas Jefferson 
Huambo 
Lobito 
Benguela 
Muhajir people 
Government 
Anatoliy Solovianenko 
Lucapa 
Cuíto 
Lubango 
Lomé 
Tunis 
Cities in Tunisia 
Tripoli 
Cities in Libya 
Benghazi 
Port Elizabeth 
Kisangani 
Sylvanus Olympio 
Togolese people 
Faure Gnassingbé 
Gnassingbé Eyadéma 
Rouen 
Tours 
Toulon 
Abu Ammaar Yasir Qadhi 
Nice 
Avignon 
Orléans 
Nancy, France 
Cities and towns in Norway 
Bergen 
Stavanger 
Trondheim 
Genoa 
Port Harcourt International Airport 
Ibadan Airport 
Toulouse–Blagnac Airport 
Airports in France 
Marseille Provence Airport 
Orly Airport 
Garganey 
Common moorhen 
Glossy ibis 
Yellow-billed stork 
Black kite 
Naruhito 
Mai Mala Buni 
Obudu 
Odukpani 
Obanliku 
Obubra 
Bekwarra 
Biase 
Calabar Municipal 
Calabar South 
Boki, Nigeria 
Etung 
Ikom 
Abi, Cross River 
Bakassi 
Yakuur 
Yala, Nigeria 
Aguata 
Awka North 
Awka South 
Anambra East 
Anambra West 
Anaocha 
Ayamelum 
Dunukofia 
Ekwusigo 
Idemili North 
Idemili South 
Ihiala 
Njikoka 
Nnewi North 
Nnewi South 
Ogbaru 
Onitsha North 
Onitsha South 
Orumba North 
Orumba South 
Oyi 
Charles de Gaulle Airport 
Nice Côte d'Azur Airport 
Lyon–Saint-Exupéry Airport 
Nantes Atlantique Airport 
Muhammad Inuwa Yahaya 
Hafsat Mohammed Baba 
Sam Mbakwe Airport 
Margaret Ekpo International Airport 
O. R. Tambo International Airport 
Cape Town International Airport 
King Shaka International Airport 
Asisat Oshoala 
Ship 
Canoe 
Hilde Holger 
Desire Oparanozie 
Yola Airport 
Sadiq Abubakar III International Airport 
Perpetua Nkwocha 
Leila Ouahabi 
Ilorin International Airport 
Katsina Airport 
Makurdi Airport 
Lesbian 
Homosexuality 
Laverne Cox 
Halimatu Ayinde 
Cairo International Airport 
Hurghada International Airport 
Hurghada 
Luxor 
Karnataka 
Ali Khamenei 
Vicky Losada 
Tallinn 
Beth Mead 
Alaba Jonathan 
Mohammed Inuwa Wushishi 
Aldana Cometti 
Maureen Mmadu 
Alex Morgan 
Automatic taxobox 
Gabrielle Onguéné 
Megan Rapinoe 
Cédric Bakambu 
Adam Ounas 
Sadio Mané 
Senegalese people 
Kenneth Omeruo 
Bogotá 
Medellín 
Cities in Colombia 
Colombia 
Youcef Belaïli 
Chidozie Awaziem 
Samuel Chukwueze 
Cartagena, Colombia 
Sofiane Feghouli 
Ramy Bensebaini 
Islam Slimani 
Andy Delort 
Raïs M'Bolhi 
Gongola River 
Olivier Verdon 
Stéphane Sessègnon 
Beninese footballers 
Beninese people 
Moïse Adiléhou 
Mickaël Poté 
Youssef Msakni 
Wahbi Khazri 
Tunisian footballers 
Tunisian people 
Naïm Sliti 
Yassine Meriah 
Ferjani Sassi 
Kara Mbodji 
Lamine Gassama 
Idrissa Gueye 
Ismaïla Sarr 
Roger Federer 
Kalidou Koulibaly 
Cheikhou Kouyaté 
Abdoulaye Diallo 
Novak Djokovic 
M'Baye Niang 
Keita Baldé 
Badou Ndiaye 
Salif Sané 
Saliou Ciss 
Youssouf Sabaly 
Habib Diallo 
Mbaye Diagne 
Alfred Gomis 
Moussa Wagué 
Édouard Mendy 
Baghdad Bounedjah 
Ismaël Bennacer 
Franck Kessié 
Ivorian footballers 
Romain Métanire 
Malagasy footballers 
Malagasy people 
Ibrahim Amada 
Metz 
Islands of Finland 
Boris Johnson 
Kenyan footballers 
Kenyan people 
Tangier 
Marrakesh 
Salé 
Sociology 
Madonna 
Minneapolis–Saint Paul 
Mississippi River 
Arkansas 
Uruguay 
Paraguay 
Cities in Paraguay 
Nicaragua 
Managua 
Cities in Nicaragua 
Nicaragua 
Pedro Sánchez 
Ahmadu Umaru Fintiri 
Sultan Bello Mosque 
Governors of Lagos State 
Babajide Sanwo-Olu 
Bala Mohammed 
Ibrahim Gaidam 
Governors of Yobe State 
Abdullahi Sule 
Babagana Umara Zulum 
Bello Matawalle 
Governors of Zamfara State 
Emeka Ihedioha 
Governors of Imo State 
Femi Gbajabiamila 
Governors of Cross River State 
Dapo Abiodun 
Governors of Ogun State 
Seyi Makinde 
Governors of Oyo State 
Hafiz Abubakar 
Maikanti Baru 
Isa Ali Pantami 
Paul Pogba 
Nigerian people 
Governors of Kaduna State 
American musicians 
Ramatu Tijjani Aliyu 
Fez, Morocco 
Infobox language 
Longitem 
Infobox language/genetic 
Infobox language/family-color 
Cities in Mexico 
Mexico 
Hameed Ali 
Regions of Niger 
Bloemfontein 
Meknes 
Quebec City 
Quebec 
Climate 
Governors of Kano State 
Ngozi Okonjo-Iweala 
Mongol Empire 
Daudawa 
Inuwa Kashifu Abdullahi 
Mahmud Shinkafi 
Ahmad Sani Yerima 
Gobarau Minaret 
Sultanate of Damagaram 
Jammu and Kashmir 
States and union territories of India 
Azman Air 
Aso Villa 
Arik Air 
Aero Contractors 
Air France 
Lufthansa 
British Airways 
Heathrow Airport 
Airports in the United Kingdom 
Gatwick Airport 
Kyoto 
Hindi 
DVD player 
Coord 
Coord missing 
Coordinates 
No globals 
Math 
Italic title 
Italic title 
Federal University, Dutsin-Ma 
Borno State University 
Umaru Musa Yar'adua University 
Football player 
Barmani Choge 
Rashidun 
Aisha 
Joko Widodo 
Gabriel 
Noah 
Adam 
Abel 
Cain 
Cohabitation 
Hassan Katsina 
Usman Nagogo 
Illiya Bisalla 
Buka Suka Dimka 
Div col 
Div col end 
Shehu Musa Yar'Adua 
Murtala Nyako 
Idris Alooma 
Aissa Koli 
Bilala people 
Ibn Furtu 
Njimi 
Yobe River 
Damasak 
Gashua 
Dunama Dabbalemi 
Kotoko kingdom 
Mandara people 
Mandara Kingdom 
Abbala 
Tin Hinan 
Rana 
Second 
Chimamanda Ngozi Adichie 
Queen Insu 
Muhammad Auwal Albani Zaria 
Dawud of Kanem 
Abdullah II of Kanem 
Ahmad 
Ali II of Bornu 
Bir I of Kanem 
Bir II of Kanem 
Dunama I 
Dunama IX Lefiami 
Hummay 
Ibrahim IV of Bornu 
Addis Ababa Bole International Airport 
Ethiopian Airlines 
Turkish Airlines 
American Airlines 
Singapore Airlines 
Qatar Airways 
United Airlines 
Delta Air Lines 
Southwest Airlines 
China Southern Airlines 
China Eastern Airlines 
All Nippon Airways 
Ryanair 
Dictionary 
Air China 
Emirates 
Dubai 
Abu Dhabi 
Abu Dhabi 
Sharjah 
Hartsfield–Jackson Atlanta International Airport 
Beijing Capital International Airport 
Tammy Abraham 
Afua Kobi 
Abiy Ahmed 
Hailemariam Desalegn 
Meles Zenawi 
Haneda Airport 
Airports in Japan 
Cyril Ramaphosa 
Jacob Zuma 
Fikayo Tomori 
Mohamed Morsi 
Hosni Mubarak 
Anwar Sadat 
Gamal Abdel Nasser 
Shanghai Pudong International Airport 
Guangzhou Baiyun International Airport 
Maria II Zaccaria 
Aderonke Kale 
Daurama 
Zulu Sofola 
Maitatsine 
Yan Tatsine 
Atheism 
Bucephalus 
Alexander the Great 
Yusuf al-Qaradawi 
Russian language 
Jomo Kenyatta 
Kisumu 
Mwanza 
Nampula 
Beira, Mozambique 
Bulawayo 
Bouaké 
Mohammed Omar 
Antarctica 
Kashmir conflict 
Atlantic Ocean 
FIFA 
Association football 
Western Asia 
Kurds 
Jews 
List of Governors of Katsina State 
African immigration to Europe 
List of state governors of Nigeria 
Mawlid 
Migration 
Islamic calendar 
Dhu al-Hijjah 
Hagar in Islam 
Yahaya Abubakar 
Anthony Olubunmi Okogie 
Muhammad Wakili 
Seriki Williams Abass 
Kudirat Abiola 
Abubakar Garbai of Borno 
List of banks in Nigeria 
Tzuyu 
Harassment 
Ahmad Abubakar 
Mohammed Bello Abubakar 
Jama'atu Nasril Islam 
List of Sultans of Sokoto 
Abdullahi Adamu 
Governor 
Lateef Adegbite 
Ghanaians in Germany 
Badshahi Mosque 
Hama Amadou 
Namaqua dove 
Four-banded sandgrouse 
African openbill 
Black stork 
Intermediate egret 
Sunbird 
Senegal coucal 
Ruff 
Gao 
Sudan golden sparrow 
Rose-ringed parakeet 
Laughing dove 
Woodpecker 
Tuwon masara 
Bean 
Fort Saint Anthony 
Bourg-la-Reine 
Pornichet 
Édouard Balladur 
Companions of the Prophet 
List of Sahabah 
List of non-Arab Sahabah 
Bilal ibn Rabah 
Sumayyah bint Khabbat 
Wahshi ibn Harb 
Ayman ibn Ubayd 
Usama ibn Zayd 
Salman the Persian 
Fayruz al-Daylami 
Zunairah al-Rumiya 
Suhayb the Roman 
Al-Baqi' 
Maria al-Qibtiyya 
Abbad ibn Bishr 
Abdullah ibn Ja'far 
Abdul-Rahman ibn Abi Bakr 
'Abd al-Rahman ibn 'Awf 
Ibn Abbas 
Umm Ayman 
Abdullah ibn Abd al-Muttalib 
Aminah 
Abd al-Muttalib 
List of airlines of Nigeria 
List of airports in Niger 
List of sovereign states and dependent territories in Africa 
Abd-Allah ibn Abd-Allah ibn Ubayy 
Abd Allah ibn Amr ibn al-As 
Abd Allah ibn al-Zubayr 
Abdullah ibn Hudhafah as-Sahmi 
Abd-Allah ibn Jahsh 
Abdullah ibn Masud 
Abdullah ibn Suhayl 
Abdullah ibn Salam 
Abdullah ibn Umar 
Abd-Allah ibn Umm-Maktum 
Abu Hurairah 
Abu Jandal ibn Suhayl 
Abbas ibn Abd al-Muttalib 
Abu Ayyub al-Ansari 
Amir ibn Fuhayra 
Abu Darda 
Education in Germany 
Mountain 
Migration from Ghana to Germany 
Eminem 
Diori Hamani International Airport 
Airports in Niger 
Mano Dayak International Airport 
Maradi Airport 
Gaya 
Diffa Airport 
Dosso Airport 
Dogondoutchi Airport 
Iferouane Airport 
Iferouane 
Kabul 
Arlit Airport 
Dirkou Airport 
Dirkou 
List of newspapers in Azerbaijan 
Gaya Airport 
Goure Airport 
Goure 
Gaya, Niger 
La Tapoa Airport 
Wikimedia Foundation 
Maine-Soroa Airport 
Ouallam Airport 
A. P. J. Abdul Kalam 
Tessaoua Airport 
Tessaoua 
Mainé-Soroa 
Ouallam 
Murtala Square 
Tillabéri 
Tillabéri Department 
Arlit Department 
Bilma Department 
Tchirozerine Department 
Diffa Department 
Mainé-Soroa Department 
Villages in Sri Lanka 
Sri Lanka 
Ahmadiyya 
Cannabidiol 
Intercontinental Cup 
Africans in Malaysia 
Badarawa, Kaduna 
Urdu 
Detroit 
Nuhu Gidado 
Dahiru Mohammed 
Isa Yuguda 
Kainji languages 
Adamawa languages 
Plateau languages 
Chadic languages 
Reed cormorant 
White-billed buffalo weaver 
Southern red bishop 
African sacred ibis 
Purple heron 
Mallard 
Knob-billed duck 
African jacana 
Senegal parrot 
Saddle-billed stork 
Thomas Sankara 
Red-billed firefinch 
Burhinus 
Black-bellied bustard 
Black-headed heron 
Vidua 
Arabian bustard 
Long-tailed glossy starling 
Christmas 
Tchirozerine 
Arlit 
Mathematics 
Nura M Inuwa 
Grey parrot 
Zinder Airport 
Selebobo 
Davido 
Atlanta 
Mumuye language 
Sylvain Tesson 
Twin 
Tillabéri Airport 
Tahoua Airport 
Téra Airport 
Téra 
Téra Department 
Tera 
Cyperus dives 
Digitaria iburua 
Mayahi Department 
Madarounfa Department 
Ficus citrifolia 
Madarounfa 
Mayahi 
Dakoro 
Dakoro Department, Niger 
Alysicarpus vaginalis 
Amaranthus caudatus 
Ansellia 
Antiaris 
Cola acuminata 
Rüppell's vulture 
Stone partridge 
Abyssinian ground hornbill 
Green wood hoopoe 
Rock dove 
Tortoise 
Days of the week 
Gyong language 
Ut-Ma'in language 
Shuwa-Zamani language 
St. Peter's Basilica 
Tessaoua Department 
Aguie Department 
Aguie 
Guidanroumdji 
Guidan Roumdji Department 
Boboye Department 
Dogondoutchi Department 
Dosso 
Dosso Department 
Gaya Department 
Loga Department 
Loga, Niger 
Loga 
Milicia excelsa 
Vodafone Ghana 
Digitaria exilis 
Eleusine coracana 
Papaya 
Abu Basir 
Abdullah ibn Rawaha 
Abalak 
Abalak Department 
Birni-N'Konni Department 
Bouza Department 
Bouza 
Anti-balaka 
Omoyele Sowore 
Human rights defender 
Walid ibn al-Mughirah 
Abu Dujana 
Abu Musa al-Ash'ari 
Persian language 
Basra 
Séléka 
Kufa 
Najaf 
Cities in Iraq 
Sharia 
Sayf ibn Umar 
Daniel in Islam 
Muawiyah I 
Amina J. Mohammed 
António Guterres 
Jamal Khashoggi 
Journalist 
Muhammad ibn Zakariya al-Razi 
Shura 
Allegiance 
Man 
Caliphate 
Muhammad's wives 
Muhammad's children 
Polci language 
Ayobami Adebayo 
Damlanci language 
Kubi language 
Ɓeele language 
Bole language 
Deno language 
Gera language 
Giiwo language 
Ngamo language 
Kwaami language 
Yiwom language 
Sha language 
Ngizim language 
Ajawa language 
Warji language 
Diri language 
Kariya language 
Mburku language 
Miya language 
Siri language 
Zumbun language 
Kir-Balar language 
Geji language 
Dass language 
Fula language 
Saya language 
Mande languages 
Busa language 
Shanga language 
Kyenga language 
Bozo language 
Dendi language 
Qasim ibn Muhammad 
Ruqayyah bint Muhammad 
Dikaka language 
Tha language 
Abdullah ibn Muhammad 
Ibrahim ibn Muhammad 
Bariba language 
Umm Kulthum bint Muhammad 
Paʼa language 
Jarawa language 
Bade language 
Jibu language 
Nupe language 
Dibo language 
Rayhana bint Zayd 
Shoo-Minda-Nye language 
Yankam language 
Sur language 
Lere language 
Kudu-Camo language 
Jere language 
Zora language 
Gyem language 
Gamo-Ningi language 
Pyam language 
Reshe language 
Eastern Acipa language 
Kambari languages 
Laru language 
Lopa language 
Gwamhi-Wuri language 
Damakawa language 
Dungu language 
Ziriya language 
Bina language 
Lela language 
2020 
Kreutz sungrazer 
Time 100 
Ottoman Empire 
Abkhazia 
Ipomoea nil 
Roselle 
Leek 
Zanthoxylum zanthoxyloides 
Barley 
Dioscorea alata 
Khaya senegalensis 
Opuntia ficus-indica 
Piper guineense 
Coleus rotundifolius 
Potato 
Thespesia populnea 
Theobroma cacao 
Syzygium guineense 
Vigna vexillata 
Ziziphus abyssinica 
Trema orientalis 
Coleus esculentus 
Khaya grandifoliola 
Laccosperma secundiflorum 
Kyllinga 
Cymbopogon schoenanthus 
Cordia africana 
Erythrophleum africanum 
Phyla nodiflora 
Panicum repens 
Senna italica 
Setaria verticillata 
Tetrapleura tetraptera 
Dioscorea dumetorum 
Dioscorea cayennensis 
Dioscorea bulbifera 
Parkia biglobosa 
Pearl millet 
Solanum anguivi 
Raphia sudanica 
Ipomoea asarifolia 
Tofa 
Imperata cylindrica 
Coconut 
Combretum glutinosum 
Abu al-As ibn al-Rabi' 
Umayr ibn Sa'd al-Ansari 
Umayr ibn Wahb 
Umamah bint Zainab 
Khadija bint Khuwaylid 
Umm Hakim 
Umm Haram 
Battle of Yarmouk 
Battle of Badr 
Kafir 
Ubayd-Allah ibn Abd-Allah 
Byzantine Empire 
Ubaydah ibn al-Harith 
Ubadah ibn al-Samit 
Amr ibn Hurayth 
Abu Dharr al-Ghifari 
Banu Ghifar 
Fadl ibn Abbas 
Bajoga 
Kabir Garba Marafa 
Abdullahi Abubakar Gumel 
Kabiru Ibrahim Gaya 
Kurfi Umaru 
Ahmad Babba Kaita 
Ibrahim Hassan Hadejia 
Danjuma Laah 
Lawal Yahaya Gumau 
Abdullahi Ibrahim Gobir 
Abubakar Kyari 
Malam Wakili 
Sulaiman Mohammed Nazif 
Illela 
Illela, Niger 
Illela Department 
Keita 
Keita, Niger 
Keita Department 
Usman Bayero Nafada 
Zara Moussa 
Safiath 
Qasem Soleimani 
Madaoua 
Madaoua Department 
Tahoua Department 
Tchintabaraden Department 
Tchintabaraden 
Ali Jita 
Album 
Nigerien musicians 
Musician 
Birni N'Gaouré 
Filingue 
Filingue Department 
Towns in Spain 
Zarma language 
List of rulers of Oman 
Abrus precatorius 
2015 Zaria massacre 
Zaria Quds Day massacres 
Islamic Movement 
Kollo 
Kollo Department 
Kollo, Niger 
Ouallam Department 
Say 
Say Department 
Say, Niger 
Shia Islam in Nigeria 
Goure Department 
Magaria Department 
Magaria 
Matameye 
Matameye Department 
Mirriah Department 
Mirriah 
Blaise Diagne International Airport 
N'Djamena International Airport 
Nigerian government officials 
Asylum in Germany 
Lists based on Wikidata 
Maintenance category 
Amir al-Mu'minin 
Siege of Jerusalem 
2017 
2016 
2015 
2014 
2013 
2012 
2011 
2010 
2009 
2008 
2007 
2006 
2005 
2004 
2003 
2002 
2001 
2000 
1999 
1998 
1997 
1996 
1995 
1994 
1993 
1992 
1991 
1990 
1989 
1988 
1987 
1986 
1985 
1984 
1983 
1982 
1981 
1980 
1979 
1978 
1977 
1976 
1975 
Bauchi State Airport 
Afzelia africana 
Adenodolichos paniculatus 
Cadaba farinosa 
Cenchrus biflorus 
Akure Airport 
Benin Airport 
Minna Airport 
Zaria Airport 
Yakubu Gowon Airport 
Akwa Ibom Airport 
Dutse International Airport 
Nnewi 
Iseyin 
Miyar kuka 
Warri Airport 
Asaba International Airport 
Jalingo Airport 
Sir Ahmadu Bello International Airport 
Tuwo shinkafa 
Zanzibar 
Qadiriyya 
Abdul Qadir Gilani 
Ogbomosho 
Ilesa 
Zungeru 
Bari 
Venice 
Leonardo da Vinci–Fiumicino Airport 
Milan Malpensa Airport 
Pointe-Noire 
Freetown 
Sierra Leone 
Daniellia oliveri 
Amala 
Yoruba people 
Noodle 
Funkaso 
Sani Kaita 
Defence Industries Corporation of Nigeria 
Cipu language 
Ficus ingens 
Dubai International Airport 
Abu Dhabi International Airport 
Sharjah International Airport 
Abd Allah ibn Khazim al-Sulami 
Siege of Uthman 
Steve Adams 
Mozdahir 
Cherif Mohamed Aly Aidara 
Steven Baker 
Occitanie 
Vegetable 
Helen Keller 
Lawal Hassan Anka 
Mahdi Aliyu Gusau 
Rahama Sadau 
Hafsat Idris 
Nuhu Abdullahi 
Politician 
Ibn Qayyim al-Jawziyya 
Damascus 
Idris Abubakar 
Abok Izam 
Patoo Abraham 
Datti Abubakar 
Haruna Abubakar 
Muhammed K. Abubakar 
Joseph Abulu 
Sophia 
Normandy 
Caen 
Angers 
Pays de la Loire 
Juba 
Bissau 
Koh-i-Noor 
Berbers 
Tharparkar 
Minute 
Félix-Houphouët-Boigny International Airport 
Gitega 
Sikasso 
Mopti 
Abdukadir Abdulsalam 
Sheikh Ahmed Abdullah 
Ahmed Aboki Abdullahi 
Magaji Abdullahi 
Dan Plato 
Koutiala 
Kayes 
Farouk Lawan 
Naziha al-Dulaimi 
Bogaletch Gebre 
Islam Bibi 
Malala Yousafzai 
Miriam Rodríguez Martínez 
Aamir Khan 
Josefa Francisco 
Maria Verónica Reina 
Faiza Jama Mohamed 
Nidal Al Achkar 
Luisa Cuesta 
Dior Fall Sow 
Karina Pankievich 
Hadja Saran Daraba Kaba 
Nanfadima Magassouba 
Isra Hirsi 
Emna Mizouni 
Bilkisu Yusuf 
Bilkisu Funtuwa 
Bilkisu Yusuf 
Amina Mama 
Hafsa bint Umar 
Sian Williams 
Ayisha Osori 
Aminatou Haidar 
Maryam Abacha 
Anna Sharyhina 
Karla Avelar 
Randa Siniora 
Guadalupe Campanur Tapia 
Ros Sopheap 
Eleanor Roosevelt 
Aminu Ado Bayero 
Coronavirus disease 2019 
Selena Rocky Malone 
Shakira 
Mohammed V International Airport 
Marrakesh Menara Airport 
Ameera al-Taweel 
Eve 
Amira Mohamed Ali 
Amina Wadud 
Nouakchott 
Panama 
Panama City 
Panama 
Asiya 
Reem Frainah 
Halimah Yacob 
Grace Oladunni Taylor 
Ibrahim Baré Maïnassara 
Nigerien military personnel 
Victoria, Seychelles 
Cities in Panama 
Seychelles 
Maymunah bint al-Harith 
Umm Salama 
Maryam Monsef 
COVID-19 pandemic in Nigeria 
Moroni, Comoros 
Katherine Maher 
List of heads of state of Nigeria 
Jessica Chastain 
Mother Teresa 
Maria Montessori 
Sameera Moussa 
Sameera Reddy 
Samira Ahmed 
Maya Angelou 
Safiya Songhai 
Plainlist 
Color box 
Venezuela 
Guyana 
Suriname 
Noura Al Kaabi 
Khadija Arib 
Paramaribo 
Cities in Suriname 
Suriname 
Georgetown, Guyana 
Guyana 
Khadija Mastoor 
Khadijah Farrakhan 
Federal Government College, Kaduna 
Sardauna Memorial College 
Nuhu Bamalli Polytechnic 
Essence International School 
List of Ahmadu Bello University alumni 
Dahiru Usman Bauchi 
Air Force Institute of Technology 
Greenfield University 
National Open University of Nigeria 
Kaduna United F.C. 
Amna Al Qubaisi 
Ahmad Abubakar Gumi 
Kathmandu 
Bishkek 
Federal College of Education, Zaria 
Fever 
Cough 
Breathing 
Saliva 
Salamatu Hussaini Suleiman 
Queen of Sheba 
Basmah bint Saud Al Saud 
Nur-Sultan 
Hamza ibn Abdul-Muttalib 
Hamid Algabid 
List of prime ministers of Niger 
Yusuf Barnabas Bala 
Khalilah Ali 
Khalilah Sabra 
Zainab al Ghazali 
Zainab Masood 
Zainab bint Muhammad 
Sakina Jaffrey 
Sakina Samo 
Umm al-Banin 
Ümmü Kiraz 
Ruqayyah Ahmed Rufa'i 
Saloma 
Jamila Woods 
Abida Parveen 
Salou Djibo 
Firdausi Qadri 
Pyongyang 
Phnom Penh 
Lucy Liu 
Niger Armed Forces 
Ulaanbaatar 
Isaias Afwerki 
Jordana Brewster 
Helena Bonham Carter 
Ouma Laouali 
Aichatou Ousmane Issaka 
Taoyuan, Taiwan 
Taichung 
National Guard of Niger 
Kaohsiung 
Tainan 
Shijiazhuang 
Harbin 
Nanyang, Henan 
List of cities in Niger 
Assodé 
Zarah Sultana 
Sultana 
Aisha Tyler 
Princess Margaret, Countess of Snowdon 
Aishwarya Rai Bachchan 
Grace Kelly 
Ayourou 
Football in Niger 
Nigerien Football Federation 
Toulou Kiki 
Malbaza 
Disambiguation pages 
Lucien Bouchardeau 
Sahel SC 
Universal Declaration of Human Rights 
Nathalie Emmanuel 
Elsa Pataky 
Abubakar Mahmud Gumi Market 
Arewa House 
Idris Shaaba Jimada 
Ministries of Kaduna State 
List of hospitals in Niger 
Don Omar 
Bouli Ali Diallo 
Aarhus 
Aalborg 
Odense 
Frederiksberg 
Umm Sulaym bint Milhan 
Vin Diesel 
Tagdal language 
Shettima Mustapha 
Cities in Afghanistan 
Afghanistan 
Herat 
Kandahar 
Usman Baba Pategi 
COVID-19 pandemic in Niger 
Mazar-i-Sharif 
Jalalabad 
Tirana 
Cities in Albania 
Albania 
Skopje 
Cities in North Macedonia 
North Macedonia 
Aminah Robinson 
Kilab ibn Murrah 
Sani Yahaya Jingir 
Abu Ubaidah ibn al-Jarrah 
Tyrese Gibson 
Andhra Pradesh 
Arunachal Pradesh 
Assam 
Bihar 
Chhattisgarh 
Goa 
Gujarat 
Anya Chalotra 
Jodhi May 
Haryana 
Himachal Pradesh 
Jharkhand 
Kerala 
Madhya Pradesh 
Maharashtra 
Manipur 
Mizoram 
Lemon 
Al-Tirmidhi 
Nagaland 
Odisha 
Punjab, India 
Meghalaya 
Rajasthan 
Ministry of Agriculture 
Sikkim 
Tamil Nadu 
Telangana 
Tripura 
Uttar Pradesh 
Abu Dawood 
Al-Bayhaqi 
Ibn Hajar al-Asqalani 
Ibn Hazm 
Islamic University of Madinah 
El-Kanemi Warriors F.C. 
El-Kanemi Stadium 
Muhammad al-Amin al-Kanemi 
Uttarakhand 
West Bengal 
Andaman and Nicobar Islands 
Puducherry 
Puducherry 
Lakshadweep 
Desmond Doss 
International Humanitarian City 
Dehradun 
Kochi 
Kabiru Gombe 
Bougainville Island 
Prime Minister of Nigeria 
Stella Obasanjo 
Ladi Kwali 
Kudirat Kekere-Ekun 
Makassar 
Fati Lami Abubakar 
Fukuoka 
Kobe 
Kawasaki, Kanagawa 
Sadiya Umar Farouq 
Ramatu Baba 
Yahaya Kuta 
Budapest 
Cities in Hungary 
Hungary 
Taribo West 
Bucharest 
Cities in Romania 
Romania 
Sofia 
Cities in Bulgaria 
Bulgaria 
Rita Orji 
Ire Aderinokun 
Ozak Esu 
Rabia Salihu Sa'id 
Yewande Akinola 
Ebele Ofunneamaka Okeke 
Podgorica 
Zagreb 
Cities in Croatia 
Croatia 
Funke Egbemode 
Cities in Montenegro 
Montenegro 
Blessing Liman 
Mojisola Adekunle-Obasanjo 
Itunu Hotonu 
Uche Jombo 
Funke Akindele 
Funmi Iyanda 
Mercy Abang 
Kiki Mordi 
Abike Dabiri 
Lola Omolola 
Lola Ogunnaike 
Didi Akinyelure 
Anike Agbaje-Williams 
Lamide Akintobi 
Theresa Bowyer 
Julie Coker 
Aisha Falode 
Molara Wood 
Sokari Ekine 
Eugenia Abu 
Adaora Udoji 
Minna Salami 
Oluremi Oyo 
Adaora Onyechere 
Kofoworola Bucknor 
Adesewa Josh 
Aisha Augie-Kuta 
Titilope Sonuga 
Adeola Fayehun 
Moji Makanjuola 
Ruona J. Meyer 
Chika Oduah 
Oyin Oladejo 
Judy Bell-Gam 
Bibi Bakare-Yusuf 
Abdulkareem Baba Aminu 
Patience Okoro 
Olamide Toyin Adebayo 
Sammy Oziti 
Queen Obisesan 
Oluwatoyosi Ogunseye 
Femi Oke 
Lawrence Anini 
Kyiv 
Farida Waziri 
Krystal Okeke 
Bimbo Oloyede 
Onyeka Onwenu 
Adesuwa Onyenokwe 
Chioma Ajunwa 
Aisha Abubakar Abdulwahab 
Minsk 
Cities in Belarus 
Belarus 
Porto 
Achille Mbembe 
Hafsat Abiola 
Kandake 
Mussasa 
Sarah Trimmer 
Anne Frank 
Mary Margaret O'Reilly 
Sabrina Sidney 
Hadiza Zakari 
Princess Alice of Battenberg 
Nandabunga 
Orompoto 
Okinka Pampa 
Enya 
Sofiat Arinola Obanishola 
Amin Yop Christopher 
Ruth Perry 
Peace Orji 
Zainab Damilola Alabi 
Dorathy Mato 
Zainab Momoh 
Daisy Danjuma 
Bilikis Abiodun Otunla 
Safiya Hussaini 
Halima Atete 
Amanda Ebeye 
Eku Edewor 
Chika Lann 
Omowumi Dada 
Omawumi 
Regina Daniels 
Anna Banner 
Mercy Aigbe 
Queeneth Agbor 
Afro Candy 
Margaret Oguntala 
Omotunde Adebowale David 
Lola Masha 
Mary Uduma 
Yemi Adamolekun 
Toyin Abraham 
Film director 
Toke Makinwa 
Adora Oleh 
Bimbo Akintola 
Siegfried & Roy 
John de Lancie 
Diezani Alison-Madueke 
Patti Boulaye 
Palau 
Federated States of Micronesia 
Marshall Islands 
Nauru 
Bimbo Ademoye 
Soldier 
Jihad 
People's Democratic Party 
Ogwashi Ukwu 
Eniola Badmus 
Liz Anjorin 
Lilian Afegbai 
Taiwo Ajai-Lycett 
Tope Oshin 
Titilope Gbemisola Akosa 
Tonga 
Samoa 
Dayo Oyewusi 
Ramatu Yakubu 
Onyeka Azike 
Grace Garba 
Farida Kabir 
Jamila Abubakar Sadiq Malafa 
Idiat Amusu 
Ivy Uche Okoronkwo 
Esther Audu 
Augustina Nkem Nwaokolo 
Vanuatu 
New Zealand 
Omotade Alalade 
Wellington 
Auckland 
Hauwa Muhammed Sadique 
Maupe Ogun 
Humuani Alaga 
Iretiola Doyle 
Ini Dima-Okojie 
Lota Chukwu 
Queen Nwokoye 
Beverly Naya 
Solomon Islands 
Kiribati 
Fiji 
Tuvalu 
Muma Gee 
Rosaline Meurer 
Annie Macaulay-Idibia 
Osas Ighodaro 
Toks Olagundoye 
Nse Ikpe-Etim 
Seyi Shay 
Belize 
Guatemala 
Guatemala 
Mary Uranta 
Chelsea Eze 
Uru Eke 
Adesua Etomi 
Faith Obazuaye 
Nkiruka Florence Nwakwe 
Josephine Omaka 
Rose Aboaje 
Chikwenye Okonjo Ogunyemi 
Aniekeme Alphonsus 
Olayemi Ogunwole 
Ariyike Akinbobola 
Agatha Amata 
Yvonne Jegede 
Moet Abebe 
Bukky Wright 
Ifu Ennada 
Linda Ejiofor 
Kiki Omeili 
Tomi Odunsi 
Maiden Alex Ibru 
Patience Ibekwe Abdullah 
Princess Halliday 
Mercy Chinwo 
Yasmin Belo-Osagie 
Saratu Gidado 
Shan George 
Lanre Hassan 
Omotayo Akinremi 
Emily Odoemenam 
Isioma Daniel 
Honduras 
El Salvador 
Chioma Chukwuka 
Bassey Ikpi 
Social distancing 
Grenada 
Rights 
Saint Kitts and Nevis 
Antigua and Barbuda 
The Bahamas 
Dominica 
Dambe 
Barbados 
Kotoka International Airport 
Chișinău 
Cities and towns in Moldova 
Moldova 
Kuwait City 
Cities in Kuwait 
Kuwait 
Chittagong 
Rajshahi 
Badminton 
Sarh 
Abéché 
Airborne transmission 
Hand washing 
Vaccination 
Hagia Sophia 
Cult image 
Zayn Africa 
Lagos Terminus railway station 
Railway stations 
Transport 
Tolulope Arotile 
Telugu language 
Marathi language 
Photograph 
List of former mosques in Spain 
Video 
Rotterdam 
Veliko Tarnovo 
Tamale, Ghana 
Flag of Nigeria 
Coat of arms of Nigeria 
Flags of Africa 
Flags of Asia 
Flags of Europe 
Leila Aboulela 
Muhammad Ali 
Oceania 
UNESCO 
Culture 
Alhassan Yusuf 
Modibo Keita International Airport 
Rochas Foundation 
Hausa architecture 
Kitwe 
List of Hausa people 
Kano State Hisbah Corps 
Ndola 
Kano State University of Technology 
Kano State House of Assembly 
Barau I Jibrin 
Thomas Sankara International Airport Ouagadougou 
Arewa 
Yau Usman Idris 
Tahoua I 
Jigawa Golden Stars F.C. 
Jigawa State House of Assembly 
Kakuri 
Bauchi Emirate 
Katsina United F.C. 
Kigali International Airport 
Bujumbura International Airport 
Jomo Kenyatta International Airport 
List of Kannywood actors 
Kannywood Awards 
Charles Egbu 
Lilongwe International Airport 
Air Peace 
Dana Air 
Overland Airways 
Air India 
Adamu Adamu 
Yusuf Sulaiman 
Saleh Mamman 
Rotimi Amaechi 
Bashir Salihi Magashi 
Naziru M Ahmad 
Mohammed Umar Bago 
Zainab Maina 
Musa Mohammed Sada 
Ibom Air 
Tchadia Airlines 
Asky Airlines 
Katsina University 
Abdullahi Balarabe Salame 
Niger Airlines 
Yaoundé Nsimalen International Airport 
RwandAir 
Amadou Moutari 
Battle of Uhud 
Gates of Hausa kingdoms 
Battle of the Trench 
Custodian of the Two Holy Mosques 
Banu Nawfal 
Haq TV 
Habib al-Ajami 
Abdullah ibn Atik 
Camair-Co 
Air Côte d'Ivoire 
Kamata Mosque 
Abba Kabir Yusuf 
Luis Suárez 
Dora Akunyili 
Twitter 
Instagram 
Adetokunbo Kayode 
Olugbenga Ashiru 
Labaran Maku 
Peter Godsday Orubebe 
God Bless Our Homeland Ghana 
Karidjo Mahamadou 
Brigi Rafini 
Marou Amadou 
Akosombo Dam 
Nii Amaa Ollennu 
COVID-19 pandemic in Ghana 
Government of Ghana 
Fidelity Bank Nigeria 
The Big Six 
Jaiz Bank 
Gold Coast 
Nafisat Abdullahi 
Jumia 
Kwame Nkrumah 
Bangui M'Poko International Airport 
Kenya Airways 
Royal Air Maroc 
Nigerian Railway Corporation 
Nkatie Cake 
Nana Yaa Serwaa Sarpong 
Ohemaa Mercy 
The Bond of 1844 
List of villages in Kano State 
Banks 
Elizabeth Adjei 
Yaba Badoe 
Jon Fortt 
Zynnell Zuh 
Akua Sena Dansua 
Abdul Samad Rabiu 
Samia Nkrumah 
Osman Nuhu Sharubutu 
Red red 
Watari Dam 
Christian Pulisic 
Jelani Aliyu 
Siligo 
Mateo Kovačić 
Timo Werner 
Religion in Ghana 
Obuasi Gold Mine 
Year of Return, Ghana 2019 
Tano River 
Chadwick Boseman 
Ankobra River 
Dawanau market 
Sabon Gari 
Bui Dam 
Akan people 
Bichi Emirate 
Lake Bosumtwi 
Hassan Usman Katsina Polytechnic 
Hakim Ziyech 
Billy Gilmour 
Nélson Semedo 
Kepa Arrizabalaga 
N'Golo Kanté 
Earring 
Wole Soyinka 
Ken Saro-Wiwa 
Districts of Ghana 
Regions of Ghana 
Yusuf Soalih Ajura 
Rebecca Akufo-Addo 
Poloo 
Waakye 
Sickle 
Nyaho Nyaho-Tamakloe 
Electoral Commission of Ghana 
Theodosia Okoh 
Freedom Radio Nigeria 
Tema Harbour 
André Sogliuzzo 
Kabiru Muhammad Inuwa 
All People's Party 
Cardi B 
Nicki Minaj 
David Dontoh 
Kofi Ansah 
Cathedral Church of Christ, Lagos 
Nigeria Police Force 
Dauda Kahutu Rarara 
Kano State Polytechnic 
Hussaini Adamu Federal Polytechnic 
Zapp Mallet 
Mamman Daura 
James Sie 
Justin Guarini 
Ernest Attuquaye Armah 
Independence Day 
Kpekpele 
Flora Nwapa 
Kashmiris 
Tahoua II 
Nigeria national football team 
Zamfara United F.C. 
Kano Pillars BC 
Ibrahim Magu 
Askia Mohammad I 
Bolaji Abdullahi 
Mass media in Ghana 
88 
89 
90 
Language 
TY Bello 
Askia Muhammad 
Gwarzo 
Bello Hayatu Gwarzo 
Islam in Ghana 
Languages of Ghana 
Ghanaian English 
Wale Adenuga 
King Sunny Adé 
1946 births 
Alain Delon 
Ahmed Nuhu Bamalli 
Ibrahim Garba 
Peugeot 
Ford Motor Company 
Toyota 
Royal Dutch Shell 
Idahosa Trails 
Rukky Sanda 
Liz Benson 
1966 births 
1938 births 
David Nnaji 
Demographics of Ghana 
Iyabo Ojo 
Ishaya Bako 
Fuelling Poverty 
Desmond Elliot 
Teju Cole 
Maryam Abacha American University Niger 
Al-Aqsa Mosque 
Ghanaian cuisine 
Hausa koko 
Fatiha Berber 
Biyouna 
1952 births 
1974 births 
Kaduna State Governor 
Abubakar Rimi 
Anton Wilhelm Amo 
Constitution of Ghana 
Telecommunications in Ghana 
Cabinet of Ghana 
President of Ghana 
Nima, Accra 
Nadia Buari 
Ama Abebrese 
Mavis Adjei 
Beverly Afaglo 
Afia Schwarzenegger 
Ama Ampofo 
Martha Ankomah 
Ghana 
Salma Mumin 
Bimbo Oshin 
Vicky Zugah 
Nasarawa State University 
Nasarawa United F.C. 
Agadez and Arlit attacks 
Kaduna State House of Assembly 
Executive Council of Katsina State 
Jigawa State School of Midwifery 
Aprapransa 
Dalla Hill 
National Pledge Of Ghana 
Dominion of Ghana 
Gongola State 
Yobe State University 
Umar Sani 
91 
92 
93 
94 
95 
96 
97 
98 
99 
100 
Str rep 
Cinema of Ghana 
Climate of Ghana 
Sokoto State University 
Zamfara State University 
Kebbi State University of Science and Technology 
Lawan Gwadabe 
Kaduna State Judiciary 
Nasarawa State College of Education, Akwanga 
Executive Council of Nasarawa State 
Gombe State House of Assembly 
Kyinkyinga 
Ghana–Nigeria relations 
Olusegun Olutoyin Aganga 
ThetaHealing 
Bookshop House 
Tinubu Square 
Newspapers published in Nigeria 
Rajnath Singh 
Kano Municipal 
Trujillo, Peru 
Sani Umar Rijiyar Lemo 
Skyline University College 
Ayo Bankole 
End SARS 
Omo Ghetto 
Rachel Oniga 
United Nations Day 
Taiwo Hassan 
Jide Kosoko 
Yinka Quadri 
Toka McBaror 
Kemi Adetiba 
Tara Fela-Durotoye 
Genny Uzoma 
1977 births 
Infobox number/box 
Infobox number 
ConvertNumeric 
Factorization 
Infobox number/link 
Tld 
Infobox number/range 
For nowiki 
Max 
Binary 
BaseConvert 
Ordinal 
Ordinal 
Greek numeral 
Greek 
Roman 
Roman 
Ternary 
Octal 
Duodecimal 
Hexadecimal 
United Nations Honour Flag 
Judith Audu 
Girley Jazama 
Infobox organization 
Composition bar 
Plain text 
Nicole Amarteifio 
Efn-ur 
Efn 
Infobox building 
Notelist-ur 
Notelist 
David Muir 
Infobox website 
If both 
Small 
Chembox 
If then show 
Chase Elliott 
Jeff Gordon 
Climate of India 
Climate change 
Deforestation 
Intergovernmental Panel on Climate Change 
Climate sensitivity 
Ruth Ogbeifo 
Sarah Michael 
Saidat Adegoke 
Salawa Abeni 
Aishatu Dahiru Ahmed 
Aisha Ahmad Suleiman 
Abibatu Mogaji 
Abidemi Sanusi 
Amina Augie 
Aisha Ismail 
Amina Titi Atiku-Abubakar 
Marie Louise Asseu 
Bétika 
Akissi Delta 
Adrienne Koutouan 
Werewere Liking 
Sabine Pakora 
Sarah Ladipo Manyika 
Claudia Tagbo 
Aisha Abubakar 
Aishah Ahmad 
Aishatu Jibril Dukku 
Aisha Mohammed 
Chinyere Kalu 
Sarah Jibril 
Saudatu Bungudu 
Salma Phillips 
Ebun Oyagbola 
Alex Lopez 
Balkisu Musa 
Fatoumata Coulibaly 
Kuoth Wiel 
Sefi Atta 
Dolapo Osinbajo 
Bianca Odumegwu-Ojukwu 
Khairat Abdulrazaq-Gwadabe 
Semira Adamu 
Binta Bello 
Elizabeth Adekogbe 
Binta Ayo Mogaji 
Asi Archibong-Arikpo 
Asabe Vilita Bashir 
Grace Folashade Bent 
Stella Oduah 
Stephanie Okereke Linus 
Alimotu Pelewura 
Patrica Ndogu 
Naja'atu Bala Muhammad 
Monsurat Sunmonu 
Florence Ita Giwa 
Osonye Tess Onwueme 
Tobiloba Ajayi 
Gbemisola Ruqayyah Saraki 
Committee 
Rose Okoji Oko 
Funmilayo Olayinka 
Ngozi Olejeme 
Folake Olunloyo 
Kate Omenugha 
Sarah Reng Ochekpe 
Linda Osifo 
Folake Solanke 
B. R. Ambedkar 
Year nav 
Ade Hassan 
Funke Abimbola 
Ifeoma Malo 
Turai Yar'Adua 
Aishatu Madawaki 
Charity Adule 
Alash'le Abimiku 
Fatima Batul Mukhtar 
Fatimat Olufunke Raji-Rasaki 
Audrey Ajose 
Grace Alele-Williams 
Samia Akario 
Fatima Zahra Bennacer 
Wiam Dahmani 
Mouna Fettou 
Hanane el-Fadili 
Ini-Abasi Umotong 
Bilikiss Adebiyi Abiola 
Aduke Alakija 
Abiola Babatope 
Adijat Olarinoye 
Hafsat Abdulwaheed 
Adunni Ade 
Tochukwu Oluehi 
Tomilayo Adekanye 
Toni Payne 
Toyin Adewale-Gabriel 
Aladi Ayegba 
Adunni Bankole 
Loveth Ayila 
Joy Bokiri 
Uche Ekwunife 
Abi Olajuwon 
Adunni Oluwole 
Zainab Adamu Bulkachuwa 
Thelma Ekiyor 
Ngozi Eucharia Uche 
Ifeanyi Chiejine 
Rita Chikwelu 
Gloria Chinasa 
Ogonna Chukwudi 
Ijeoma Queenth Daniels 
Blessing Diala 
Tanimowo Ogunlesi 
Yetunde Teriba 
Peace Efih 
Chinwendu Ihezuo 
Anam Imo 
Ndidi Kanu 
Adejoke Ayoola 
Leila Nakabira 
Jones Arogbofa 
Milka Irene 
Sarah Kisawuzi 
Bettinah Tianah 
Stellah Nantumbwe 
Tawa Ishola 
Joy Jegede 
Uchenna Kanu 
Faith Michael 
Aloma Mariam Mukhtar 
Anna Darius Ishaku 
Olaoluwa Abagun 
Hairat Balogun 
Alice Ogebe 
Adejoke Lasisi 
Mercy Ntia-Obong 
Muizat Ajoke Odumosu 
Basirat Nahibi 
Mulikat Adeola Akande 
Flora Azikiwe 
Murjanatu Musa 
Nana Abdullahi 
Nelly Uchendu 
Maryam Babangida 
Francisca Ordega 
Chinaza Uchendu 
Evelyn Nwabuoku 
Vivian Chukwuemeka 
Vera Okolo 
Uwani Musa Abba Aji 
Ulunma Jerome 
Uchechi Sunday 
Kaylah Oniwo 
Baba of Karo 
Florence Ajayi 
Rasheedat Ajibade 
Mercy Akide 
IMDb 
Josephine Chukwunonye 
Precious Dede 
Binta Masi Garba 
Ngozi Ebere 
Hadiza Nuhu 
Nenadi Usman 
Maimunat Adaji 
Lola Shoneyin 
Margaret Ekpo 
Margaret Etim 
Rebecca Kalu 
Osinachi Ohale 
Chidinma Okeke 
Ngozi Okobi-Okeoghene 
Christy Ucheibe 
Chi-Chi Igbo 
Onome Ebi 
Bisola Aiyeola 
Sophie Alakija 
Ada Ameh 
Halima Tayo Alao 
Hadiza Lantana Oboh 
Jimmie Johnson 
Hauwa Ibrahim 
Maymunah Kadiri 
Nkechi Justina Nwaogu 
Hauwa Ali 
Joan Onyemaechi Mrakpor 
Juliet Akano 
Nkoyo Toyo 
Olabisi Afolabi 
Olaide Olaogun 
Cecelia Akagu 
Betty Apiafi 
Branwen Okpako 
Bose Kaffo 
Falilat Ogunkoya 
Kemi Adeosun 
Fati Abubakar 
Patricia Etteh 
Martha Bodunrin 
Lateefah Durosinmi 
Franca Afegbua 
Judith Amaechi 
Asabe Shehu Musa Yar'Adua 
Catherine Obianuju Acholonu 
Oluranti Adebule 
Hilda Adefarasin 
Jumoke Akindele 
Omowunmi Sadik 
Chiamaka Obuekwe 
Christy Ohiaeriaku 
Glory Emmanuel Edet 
Stella Omu 
Bisi Silva 
Taiwo Abioye 
Dina Emam 
Maryam Ciroma 
Oshoke Abalu 
Angie Abdalla 
Mervat Amin 
Olajumoke Adenowo 
Bushra 
Fifi Ejindu 
Chinwe Ohajuruka 
Yewande Omotoso 
Nwagboka 
Tosin Oshinowo 
Ola Uduku 
Jenevieve Aken 
Fatimah Tuggar 
Mariam Yalwaji Katagum 
Nancy Illoh 
Peju Layiwola 
Amarachi Okafor 
Nike Davies-Okundaye 
Lisa Folawiyo 
Wunmi Mosaku 
Ejiro Amos Tafiri 
Reni Folawiyo 
Lola Akinmade Åkerström 
Folake Olowofoyeku 
Storm colour 
Infobox event 
If empty 
If empty 
Comma separated entries 
Align 
Center 
Folake Coker 
Funlola Aofiyebi-Raimi 
Omotayo Oduntan 
Str len 
Str len/core 
Peace Uzoamaka Nnaji 
Ebitimi Agogu 
Ebiti Ndok 
Yetunde Onanuga 
Yetunde Barnabas 
Yetunde Ayeni-Babaeko 
Jumoke Oduwole 
Jumoke Odetola 
Jumoke George 
Jumoke Verissimo 
Folake Onayemi 
Zainab Gimba 
Chinyere Stella Okunna 
Yagazie Emezi 
Mercy Johnson 
Ngozi Onwurah 
Ayisat Yusuf 
Amenze Aighewi 
Sandra Achums 
Fisayo Ajisola 
Lilian Bach 
Rita Akarekor 
Gladys Akpa 
Louisa Akpagu 
Cynthia Aku 
Ajuma Ameh-Otache 
Patience Avre 
Omo-Love Branch 
Ann Chiejine 
Judith Chime 
Lilian Cole 
Courtney Dike 
Infobox grapheme 
Gloria Ofoegbu 
K 
Omoyemi Akerele 
Kande Balarabe 
Nyma Akashat Zibiri 
Laila Dogonyaro 
Florence Iweta 
Jadesola Akande 
Bunmi Kayode 
Ronke Ademiluyi 
Lydia Koyonda 
Ezinne Akudo 
Yinka Kudaisi 
Chinelo Anohu 
Bolanle Austen-Peters 
Nkiru Balonwu 
Josephine Mathias 
Funke Bucknor-Obruthe 
Omasan Buwa 
Kemi Lala Akindoju 
Valerie Ebe 
Dayo Amusa 
Joy Emodi 
Dayo Olopade 
Leila Fowler 
Omosede G. Igbinedion 
Stella Mbachu 
Nkem Akaraiwe 
Nkechi Akashili 
Onome Akinbode-James 
Mobolaji Akiode 
Joanne Aluka 
Ikponwosa Ero 
Onimim Jacks 
Ann Mukoro 
Rimini Makama 
Olusola Obada 
Ugo Njoku 
Ruth Obih 
Cecilia Nku 
Mary Odili 
Elizabeth Ogbaga 
Ezinwa Okoroafor 
Rita Nwadike 
Smaranda Olarinde 
Modupe Omo-Eboh 
Maria Usifo 
Maria Zukogi 
Victoria Onejeme 
Mariam Masha 
Diana Nwaiwu 
Becky Umeh 
Chinenye Fidelis 
Mactabene Amachree 
Promise Amukamara 
Upe Atosu 
Adanna Nwaneri 
Elizabeth Balogun 
Mary Durojaye 
Elo Edeferioka 
Adaora Elonu 
Nicole Enabosi 
Charity Opara 
Boma Ozobia 
Helen Prest-Ajayi 
Sarah Imovbioh 
Nguveren Iyorhe 
Ezinne Kalu 
Pallas Kunaiyi-Akpannah 
Nkechi Mbilitam 
Chima Nwosu 
Laraba Gambo Abdullahi 
Toyin Saraki 
Abiola Bashorun 
Sasha P 
Adaora Lily Ulasi 
Princess Peters 
Funmi Tejuosho 
Shafkat Bose Adewoyin 
Elsie Nwanwuri Thompson 
Toki Mabogunje 
Biodun Obende 
Ijeoma Obi 
Aisha Dikko 
Emueje Ogbiagbevha 
Glory Ogbonna 
Mavis Ogun 
Martina Ohadugha 
Esther Okhae 
Rosaline Elbay 
Buchi Emecheta 
Laila Fawzi 
Victoria Macaulay 
Blessing Okagbare 
Laila Elwi 
Ndidi Dike 
Atonye Nyingifa 
Sarah Ogoke 
Linda Ogugua 
Ugo Oha 
Adaku Okoroafor 
Amarachi Okoronkwo 
Nkiru Okosieme 
Rashidat Sadiq 
Cecilia Okoye 
Taiwo Odubiyi 
Florence Omagbemi 
Celestina Onyeka 
Ogechi Onyinanya 
Eberechi Opara 
Ugochi Opara 
Balaraba Aliyu Inuwa 
Mfon Udoka 
Gift Otuwe 
Olayinka Sanni 
Fausat Balogun 
Charity Reuben 
Chioma Udeaja 
Juliana Negedu 
Jasmine Nwajei 
Taiwo Rafiu 
Kehinde Olorunyomi 
Fausat Adebola Ibikunle 
Franca Brown 
Anne Njemanze 
Gift Showemimo 
Mariam Usman 
Mary Njoku 
Mariya Mahmoud Bunkure 
Adepero Oduye 
Ayo Adesanya 
Remi Abiola 
Eniola Ajao 
Ebele Okaro 
Zainab Ibrahim Kuchi 
Rofiat Sule 
Martha Tarhemba 
Helen Ukaonu 
Gloria Usieta 
Cynthia Uwak 
Ebbe Bassey 
Ibubeleye Whyte 
Sola Asedeko 
Chioma Wogu 
Rachael Yamala 
Olaitan Yusuf 
Akudo Sabi 
Sophia Omotola Omidiji 
Nwabueze Nwokolo 
Tunde Aladese 
Rachel Bakam 
Uju Okeke 
Steph-Nora Okere 
Paschaline Alex Okoli 
Oge Okoye 
Adebukola Oladipupo 
Yinka Olukunga 
Lepa Shandy 
Sharon Ooja 
Beverly Osu 
Nneka J. Adams 
Yewande Adekoya 
Bukky Ajayi 
Tonye Garrick 
Shafy Bello 
Ada Ehi 
Batile Alake 
Simi 
Maureen Solomon 
Nkiru Sylvanus 
Ugonna Umerou 
Gloria Young 
Bella Alubo 
Sarah Nnodim 
Olufunmilayo Olopade 
Sara Forbes Bonetta 
Efunsetan Aniwura 
Omu Okwei 
Efunroye Tinubu 
Yemi Adesanya 
Ayo Ayoola-Amale 
Theresa Lola 
Chioma Okereke 
Mabel Segun 
Wana Udobang 
Ijeoma Umebinyuo 
Oyinkansola Abayomi 
Nwando Achebe 
Bisi Adeleye-Fayemi 
Sandra Aguebor 
Ifi Amadiume 
Joy Isi Bewaji 
Bunmi Dipo Salami 
Ola Brown 
Ayesha Imam 
Christy Udoh 
Iheoma Obibi 
Endurance Abinuwa 
Bukola Abogunloko 
Molara Ogundipe 
Folashade Abugan 
Julie Okoh 
Kemi Adesoye 
Ayodele Olofintuade 
Kemi Adekoya 
Tosin Adeloye 
Agnes Yewande Savage 
Margaret Adebisi Sowunmi 
Sekinat Adesanya 
Clarice Ahanotu 
Yinka Ajayi 
Benedicta Ajudua 
Funmi Olonisakin 
Kudirat Akhigbe 
Chioma Opara 
Oyeronke Akindele 
Oyeronke Oyewumi 
Mary Akinyemi 
Florence Ozor 
Yemisi Ransome-Kuti 
Jennifer Uchendu 
Adanna Steinacker 
Lami Phillips 
Betty Abah 
Abisoye Ajayi-Akinfolarin 
Chief Temitope Ajayi 
Olufunke Baruwa 
Glory Alozie 
Oluwatobiloba Amusan 
Grace Anigbata 
Gloria Asumnu 
Gloria Ayanlaja 
Airat Bakare 
Margaret Bamgbose 
Ada Benjamin 
Olajumoke Bodunrin 
Onyinye Chikezie 
Rosemary Chukwuma 
Dominique Duncan 
Emem Edem 
Emilie Edet 
Abike Funmilola Egbeniyi 
Emerald Egwim 
Joan Uduak Ekah 
Florence Ekpo-Umoh 
Christy Ekpukhon 
Joy Eze 
Mary Ekpere-Eta 
Wuraola Esan 
Funmi Falana 
Feminist Coalition 
Esther Ibanga 
Esther Ijewere 
Oluyemi Fagbamila 
Simi Johnson 
Josephine Obiajulu Odumakin 
Cecilia Francis 
Iman Essa Jasim 
Mairo Jinadu 
Stephanie Kalu 
Gloria Kemasuode 
Jennifer Madu 
Mercy Eke 
Oguzoeme Nsenu 
Ngozi Nwosu 
Ngozi Nwozor-Agbo 
Ashanti Obi 
Deborah Oluwaseun Odeyemi 
Favour Ofili 
Funmilola Ogundana 
Endurance Ojokolo 
Lawretta Ozoh 
Amina Mohammed Baloni 
Blessing Igbojionu 
Adaobi Tricia Nwaubani 
Oluwaseun Osowobi 
Bukola Oriola 
Janet Okala 
Laila St. Matthew-Daniel 
Christie Ade Ajayi 
Kofoworola Ademola 
Abimbola Alao 
Uduak Archibong 
Sarah Jibrin 
Alaba Lawson 
Bose Ogulu 
Funke Oladoye 
Janet Omorogbe 
Omolara Omotosho 
Aminat Yusuf Jamal 
Pauline Ibeagha 
Ngozi Onwumere 
Halimat Ismaila 
Mary Onyali-Omagbemi 
Christy Opara-Thompson 
Oludamola Osayomi 
Agnes Osazuwa 
Uhunoma Osazuwa 
P. A. Ogundipe 
Christianah Oluwatoyin Oluwasesin 
Kofoworola Abeni Pratt 
Sarah Adebisi Sosan 
Sheila Mary Tuer 
Rosina Umelo 
Olufunlola Adekeye 
Adebukola Banjoko 
Rosaline Bozimo 
Esohe Frances Ikponmwen 
Nkemdilim Izuako 
Dulcie Ethel Adunola Oguntoye 
Modupe Irele 
Georgina Onuoha 
Carol King 
Oghenekaro Itene 
Keira Hewatch 
Olatokunbo Somolu 
Bikiya Graham-Douglas 
Idia 
Tejumade Alakija 
Iyabo Anisulowo 
Hannah Idowu Dideolu Awolowo 
Lynda Chuba-Ikpeazu 
Daisy W. Okocha 
Stella Thomas 
Meg Otanwa 
Onyeche Tifase 
Ameyo Adadevoh 
Ahebi Ugbabe 
Elizabeth Abimbola Awoliyi 
Afi Ekong 
Habibah Ruth Garba 
Nwanyeruwa 
Abimbola Amusu 
Angela Ekaette 
Joana Maduka 
Citation 
Halle 
Sadique Abubakar 
Aso Rock 
Adetoun Ogunsheye 
Esther Olukoya and Emily Ogunde 
Grace Oyelude 
Florence Seriki 
Margaret Shonekan 
Grace Eniola Soyinka 
Pamela Adie 
Maya Horgan Famodu 
Mayowa Nicholas 
Mabel Oboh 
Lilian Salami 
Simi Bedford 
Umaru Sanda Ndayako 
Uzamat Akinbile Yussuf 
Roseline Ukeje 
Nnenna Elendu Ukeje 
Eucharia Anunobi 
Eka Esu Williams 
Oluremi Tinubu 
Pauline Tallen 
Moremi Ajasoro 
Charlotte Obasa 
Princess Elizabeth Olowu 
Roseline Konya 
Tonye Briggs-Oniyide 
Patricia Akwashiki 
Rita Akpan 
Iyabo Akanmu 
Offiong Edem 
Cecilia Offiong 
Abiola Odumosu 
Kehinde Kamson 
Olufunke Oshonaike 
Roseline Osipitan 
Doyin Abiola 
Agho Obaseki 
Dupsy Abiola 
Mo Abudu 
Jackie Aina 
Nike Akande 
Toyosi Akerele-Ogunsiji 
Omowunmi Akinnifesi 
Adenike Akinsemolu 
Folorunso Alakija 
Ibukun Awosika 
Quincy Olasumbo Ayodele 
Bimbo Balogun 
Bunmi Banjo 
Banke Meshida Lawal 
DJ Cuppy 
Sola David-Borha 
Bella Disu 
Temie Giwa-Tubosun 
Atisi Owoh 
Kubrat Owolabi 
Olusegun Mimiko 
Olusegun Adejumo 
Ibidunni Ighodalo 
Amy Jadesimi 
Omobola Johnson 
Jewel Lafontant 
Oreoluwa Lesi 
Lola Maja 
Mowalola Ogunlesi 
Toun Okewale Sonaiya 
Shade Okoya 
Bola Kuforiji-Olubi 
Ukel Oyaghiri 
Mosun Filani 
Chidinma 
Demi Grace 
Dupe Olusola 
Ada Osakwe 
Owen Omogiafo 
Evelyn Oputu 
Funke Osibodu 
Toyin Sanni 
Hauwa Ojeifo 
Nigerian Customs Service 
Manouchka Kelly Labouba 
Zeresenay Berhane Mehari 
Amleset Muchie 
Ilfenesh Hadera 
Liya Kebede 
Semra Kebede 
Zeritu Kebede 
Ruth Negga 
Hanan Tarik 
Selam Tesfaye 
Fryat Yemane 
Moji Afolayan 
Funke Opeke 
Nike Oshinowo 
Bola Shagaya 
Muhammad Bala Shagari 
Joke Silva 
Bisoye Tejuoso 
Teni 
Music genre 
Miss Sahhara 
Ann-Kio Briggs 
Tiwa Savage 
Nupedia 
Jane Wall 
Dolly Unachukwu 
Abiola Segun 
Honey Ojukwu 
Ifeoma Aggrey-Fynn 
Folayegbe Akintunde-Ighodalo 
Crystal Chigbu 
Aisha Diori 
Susan Wojcicki 
Barbara Okereke 
Stella Chinyelu Okoli 
Nkiru Olumide-Ojo 
Folashade Sherifat Jaji 
Folashade Yemi-Esan 
Ramatu Yaradua 
Oby Ezekwesili 
Yinka Jegede-Ekpe 
Ini Edo 
Mary Nzimiro 
Kemi Omololu-Olunloyo 
Onyinye Ough 
Aisha Yesufu 
Priscilla Achapka 
Symbiosis 
Esther Agbarakwe 
Fulani herdsmen 
Folashade Omoniyi 
Folashade Adefisayo 
Tameka Jameson 
Doris Jacob 
Fatima Yusuf 
Modupeola Fadugba 
Modupe Ozolua 
Arunma Oteh 
Lola Ashiru 
Mohammed Abba Gana 
Aminatu Abiodun 
Idara Otu 
Emmanuel Ifeajuna 
Anthony Enahoro 
Adebayo Adedeji 
Henry Adefope 
Ojo Maduekwe 
Onyebuchi Chukwu 
Remi Fani-Kayode 
Idara Victor 
Remi Babalola 
Oluyemi Adeniji 
Mary Tombiri 
Calister Ubah 
Rufina Ubah 
Joy Udo-Gabriel 
Peace Uko 
Beatrice Utondu 
Kehinde Vaughan 
Richard Mofe-Damijo 
Tonye Princewill 
Odigha Odigha 
Onaolapo Soleye 
Nestor Binabo 
Akinwumi Adesina 
Daniel Igali 
Vincent Obasi Usulor 
Kofo Abayomi 
Josephine Anenih 
Joseph Tarka 
Oluseyi Bajulaiye 
Sylvester Ugoh 
Obi Wali 
Emmanuel Onwe 
Felix Femi Ajakaye 
Nnimmo Bassey 
Shettima Ali Monguno 
Sani Daura 
Shafi Edu 
Raymond Dokpesi 
Samuel Bassey 
Dapo Folorunsho Asaju 
Chidinma and Chidiebere Aneke 
Chigul 
Abimbola Craig 
Liz Da-Silva 
Claire Edun 
Ego Boyo 
Uche Elendu 
Jennifer Eliogu 
Eve Esin 
Destiny Etiko 
Kehinde Fadipe 
Fatima Faloye 
Henrietta Kosoko 
Ini Ikpe 
Mary Lazarus 
Uche Mac-Auley 
Mercy Ima Macjoe 
Makida Moka 
Nneka Isaac Moses 
Toyin Adegbola 
Johnson Bamidele Olawumi 
Joseph Nanven Garba 
Benjamin Adekunle 
Ibok Ekwe Ibas 
Mele Kyari 
Omololu Falobi 
Halilu Akilu 
Adeyinka Oyekan 
Geoffrey Onyeama 
Nigerian Armed Forces 
Toyin Afolayan 
Hassanat Akinwande 
Tope Alabi 
Bose Alao 
Teni Aofiyebi 
Regina Askia-Williams 
Faithia Balogun 
Minah Bird 
Monalisa Chinda 
Clarion Chukwura 
Stella Damasus 
Foluke Daramola 
Hilda Dokubo 
Rita Dominic 
Abiodun Duro-Ladipo 
Omotola Jalade Ekeinde 
Ngozi Ezeonu 
Ibinabo Fiberesima 
Kate Henshaw 
Jennifer Okere 
Khabirat Kafidipe 
Eva Mottley 
Empress Njamah 
Genevieve Nnaji 
Iyabbo Jolaade Adewuyi 
Ronke Ojo 
Patience Ozokwor 
Nike Peller 
Asele Woy 
Idowu Philips 
Hajarat Yusuf 
Ommo Clark 
Abimbola Fashola 
Toyin Raji 
Idiat Shobande 
Jill Asemota 
Sola Sobowale 
Barbara Soky 
Ibukun Odusote 
Halima Abubakar 
Victoria Nkong 
Damilola Adegbite 
Celine Loader 
Aderounmu Adejumoke 
Ijeoma Grace Agu 
Chizzy Alichi 
Uzoamaka Aniunoh 
Chineze Anyaene 
Zainab Balogun 
Kehinde Bankole 
JJ Bunny 
Caroline Chikezie 
Stephanie Coker 
Caroline Danjuma 
Lola Odusoga 
Michelle Dede 
Tonto Dikeh 
Theresa Edem 
Belinda Effah 
Dakore Egbuson-Akande 
Yvonne Ekwere 
Tamara Eteimo 
Demi Isaac Oviawe 
Somkele Iyamah 
Ruth Kadiri 
Bisi Komolafe 
Sola Kosoko 
Lola Margaret 
Tina Mba 
Titi Oyinsan 
Olajumoke Orisaguna 
Ufuoma McDermott 
Agbani Darego 
Bayray McNwizu 
Monicazation 
Anita Ukah 
Nuella Njubigbo 
Ebube Nwagbo 
Yemi Fawaz 
Emma Nyra 
Kah-Lo 
Ronke Odusanya 
Uche Ogbodo 
Daniella Okeke 
Thelma Okoduwa 
Rachael Okonkwo 
Angela Okorie 
Chioma Okoye 
Maureen Okpoko 
Princess Vitarah 
Ivie Okujaye 
Cossy Orjiakor 
Monica Ogah 
Moji Olaiya 
Juliana Olayode 
Yeka Onka 
Sylvia Oluchy 
Niniola 
Seun Omojola 
Sunkanmi 
Waje 
Jahdiel 
Lisa Omorodion 
Weruche Opia 
Yvonne Orji 
Ireti Osayemi 
Jemima Osunde 
Susan Peters 
Cynthia Shalom 
Dorcas Shola-Fapson 
Doris Simeon 
Pepi Sonuga 
Maryam Yahaya 
Diana Yekinni 
Annabella Zwyndila 
Helen Paul 
Lilian Esoro 
Chioma Toplis 
Gloria Bamiloye 
May7ven 
Yetide Badaki 
Zuwaira Gambo 
Zainab Lawal Gummi 
Talatu Yohanna 
Titilayo Laoye-Tomori 
Remi Sonaiya 
Sinatu Ojikutu 
Sa'adatu Modibbo Kawu 
Rifkatu Adamu Chidawa 
Nkeiruka Onyejeocha 
Ayo Omidiran 
Abiodun Olujimi 
Olajumoke Okoya-Thomas 
Miriam Onuoha 
Mariatu Bala Usman 
Kulu Abdullahi Sifawa 
Kikelomo Longe 
Patience Jonathan 
Nkechi Ikpeazu 
Hannatu Salihu 
Francesca Yetunde Emanuel 
Blessing Onuh 
Blessing Nsiegbe 
Badiyya Hassan Mashi 
Arinola Fatimah Lawal 
Ajibola Ponnle 
Eberechi Wike 
Adejoke Orelope-Adefulire 
Iyabo Obasanjo-Bello 
Beni Lar 
Eme Ufot Ekaette 
Asikey 
Roberts International Airport 
Moussa Maâzou 
Amina Said Ali 
Heinrich Barth 
Kashmiris of Punjab 
People 
Vivienne Roumani 
Jawal Nga 
Joelle Kayembe 
Warona Setshwaelo 
Vitalina Varela 
Ugonna Okegwo 
Blanche Bailly 
Brenda Elung 
Edith Pikwa 
Christa Eka 
Bandy Kiki 
Hortavie Mpondo 
Joséphine Ndagnou 
Okawa Shaznay 
Delly Singah 
Solange Yijika 
Rastafari 
Samantha Biffot 
Stephanie Tum 
Yolande Welimoum 
Marang Molosiwa 
Rachel Mwanza 
Véro Tshanda Beya Mputu 
Mereb Estifanos 
Helen Meles 
Habben Michael 
Caribbean 
Inessa Lee 
Ines Pellegrini 
Kirat Bhattal 
Michaela Songa 
Gertrude Webster Kamkwatira 
Joyce Mhango-Chavula 
Tapiwa Gwaza 
Avril 
Maureen Connell 
Muthoni Gathecha 
Nana Gichuru 
Nice Githinji 
Sarah Hassan 
Patricia Kihoro 
Samantha Mugatsia 
Sheila Munyiva 
Wanja Mworia 
Azziad Nasenya 
Njeri Luseno 
Janet Kirina 
Alawites 
Ibadi Islam 
Bag 
Diana C. Zollicoffer 
Flora Gomes 
Mosili Makuta 
Kurdistan 
Ngardy Conteh George 
Nadine Ibrahim 
Latefa Ahrar 
Maji-da Abdi 
Nomsa Manaka 
Nadia Fares Anliker 
Magaajyia Silberfeld 
Christiane Chabi-Kao 
Angela Aquereburu 
Lula Ali Ismaïl 
Nous aurons toute la mort pour dormir 
Yéyamba Wandzé Mdrou Ndo? 
Mounira Mitchala 
Justine Bitagoye 
Marwa Zein 
Delphe Kifouani 
Arlete Bombe 
Ladji Diakité 
Mariama Sylla 
Soumaya Akaaboune 
Denise Newman 
Marina Niava 
Isfahan Province 
Aicha Evans 
Jacqueline Wolper 
Susan Basemera 
Jill Levenberg 
Awa Sène Sarr 
Majdouline Idrissi 
Sonna Seck 
MaameYaa Boafo 
Leila Hadioui 
Chantal Youdum 
Albertine N'Guessan 
Beatrice Taisamo 
Odile Sankara 
Jesesi Mungoshi 
Mohcine Besri 
Lara Sousa 
Azwile Chamane-Madiba 
Bibi Nshimba 
Jordan Riber 
Godliver Gordian 
Barlen Pyamootoo 
Étienne Goyémidé 
Mukakamanzi Beatha 
Letekidan Micael 
Pat Nebo 
Shyaka Kagamé 
Jean-Luc Habyarimana 
Cynthia Butare 
Musanase Laura 
Munezero Aline 
Philbert Aimé Mbabazi 
Nadege Uwamwezi 
Kirenga Saphine 
Lansana Mansaray 
Nasib Farah 
Nneka Abulokwe 
List of members of the United Nations Security Council 
Ghana Infectious Disease Centre 
Buddhism 
Electricity sector in Ghana 
Sikhism 
Jainism 
Mahdavia 
Zoroastrianism 
Ghana Meteorological Agency 
Salt industry in Ghana 
Ministry of Food and Agriculture 
Webarchive 
Climate change in Ghana 
Banu Hashim 
Battle of Khaybar 
Hausa Sign Language 
Biu Emirate 
Wiktionary 
Word 
Location map 
Infobox language family 
ISO 639-1 
ISO 639-2 
Infobox writing system 
ISO 15924 code 
Nobold 
Beyoncé 
Hlist 
Citation 
Yazidis 
Gnosticism 
Yarsanism 
Mazdak 
Shinto 
Gidan Makama Museum Kano 
Bábism 
Tobago 
Nas 
University of Environment and Sustainable Development 
Council for Scientific and Industrial Research – Ghana 
Ministry of Environment, Science, Technology and Innovation 
Trinidad 
Port of Spain 
Trinidad and Tobago national football team 
Bermuda 
Steven Pruitt 
Cquote 
Lorem ipsum 
Won 
Nom 
Dead link 
Fix 
Category handler 
Mirza Masroor Ahmad 
DJ Khaled 
Ibrahim Bio 
Zakir Naik 
Bill Gates 
Infobox ethnic group 
IMDb name 
Trim 
EditAtWikidata 
Infobox food 
Str left 
Fix/category 
AchievementTable 
S-start 
S-end 
Succession box 
S-bef 
S-ttl 
S-aft 
Delink question hyphen-minus 
S-aft/filter 
S-bef/filter 
Tiv language 
Str rightmost 
Yesno 
N/a 
Jacob Gyang Buba 
S-hon 
Both 
Mary, mother of Jesus 
Virginity 
List of religions and spiritual traditions 
Muhammad Kwassau 
Petzone 
Str find 
Multiple image 
Cbignore 
Culture 
Hausa food 
2020–21 Nigerien general election 
Mohamed Bazoum 
Seyni Oumarou 
Greater color contrast ratio 
Seyni Garba 
Lang 
Language/data/iana languages 
2021 
Ahmed Lemu 
Nafata of Gobir 
EB1911 
Hide in print 
Cite EB1911 
Cite encyclopedia 
Citation needed 
' 
Str rightc 
Flatlist 
URL 
Cite magazine 
Transclude 
Climate change feedback 
Retreat of glaciers since 1850 
Joe Biden 
An Inconvenient Truth 
Peter New 
Sea level rise 
FIFA player 
WikidataCheck 
UEFA player 
Abbr 
· 
Cite AV media 
Cite wikisource/make link 
Cite bioRxiv 
Dagger 
Curlie 
Albadé Abouba 
In lang 
Daouda Malam Wanké 
Adamou Harouna 
Religion in Niger 
Baháʼu'lláh 
• 
Str sub old 
First character 
NGA 
DetailsLink 
Báb 
SfnRef 
Pending 
Sortname 
First word 
IMDb title 
Emirate of Abu Dhabi 
Cite tweet 
Clear left 
Tony Elumelu 
Sfn 
Google books 
Lang-ar 
Yesno-yes 
Str endswith 
Vcite web 
Vcite news 
YouTube 
Replace 
Authority control 
Visible anchor 
Official website 
Cite press release 
Cite court 
Wikidata 
Twitter 
World Athletics 
4TeamBracket-Tennis3 
PD-notice 
4TeamBracket-Tennis5-with 3rd 
8TeamBracket-Compact-Tennis3-Byes 
Climate change in Africa 
Climate change in the Middle East and North Africa 
Flagicon 
Flagicon/core 
Country data Sovereign Military Order of Malta 
S-non 
S-new 
S-hou 
S-aca 
S-break 
S-vac 
R 
R/ref 
Cref2 
S-off 
S-ach 
S-par 
S-inc 
Bots 
Long dash 
Tooltip 
Yesno-no 
When 
Sort 
Refn 
S-dip 
S-ppo 
S-reg 
SSRN 
Only in print 
Columns-list 
MedalistTable 
Col-3 
Col-2 
Col-4 
Col-5 
Col-begin-small 
Flagdeco 
Flagdeco/core 
Flagu 
Flagu/core 
Country data Washington, D.C. 
Doi 
JSTOR 
Lang-ff 
Lang-fr 
Lang-he 
Listen 
Emergency-bot-shutoff 
Rp 
En dash 
Spaced en dash 
FlagIOC2athlete 
Gold medal 
Silver medal 
Bronze medal 
Country data China 
Blockquote 
P2 
Football squad end 
Football squad mid 
Football squad player 
Fba/core 
Fba/list 
End 
External media 
List of states with limited recognition 
Guardian topic 
New York Times topic 
User info 
Middle East 
Western Sahara 
Bar box 
Bar percent 
Abraj Al Bait 
Single namespace 
Flag of Niger 
Cmbox 
Category other 
Polluted category 
AllMusic 
User page 
Fashionmodel 
FIAV 
You Xie 
University 
Muhammad Ibn Muhammad Al-Fulani Al-Kishwani 
Minaret 
London Gazette 
Air force 
Air force/core 
FlagCGFathlete 
CGF year 
Navy 
Navy/core 
Army/core 
Age 
Date 
Death date and age 
Flagcountry 
Flagcountry/core 
Ahmadiyya in Nigeria 
Ref label 
Rogo 
Circa 
Fbw 
Marriage 
Wbr 
Hover title 
Str ≠ len 
In string 
Str ≥ len 
Wdib 
MONTHNUMBER 
Free access 
Runner-up 
Mansur Makeup 
Senate of Nigeria 
Country data Brazil 
Flaglink/core 
Start date and age 
BillboardURLbyName 
National Assembly 
Nigerian National Assembly delegation from Kano 
Cite certification 
Certification Cite/Title 
Certification Cite/URL 
Spaces 
Infobox musical artist 
Infobox musical artist/tracking 
Infobox musical artist/color 
Location map+ 
Location map~ 
Adjara 
EThOS 
ESP 
Guria 
Imereti 
Sic 
Editnotice 
UN document 
Leo Irabor 
Isiaka Oladayo Amao 
Ibrahim Attahiru 
Awwal Zubairu Gambo 
US$ 
NoteTag 
Cite web/French 
Cite Quran 
Bibleverse 
Bibleverse-nb 
Rowan Atkinson 
Time ago 
Time ago 
Kamala Harris 
Garba Shehu 
IND 
MEX 
BRA 
TUR 

